<?php
/** Real PHP views with synthetic company data, no provider/network requests. */
declare(strict_types=1);
ob_start();require __DIR__.'/operational-access-check.php';ob_end_clean();
require __DIR__.'/../ecomkit-vuikhoe/vendor/autoload.php';
define('ECOMKIT_VUIKHOE_FILE',__DIR__.'/../ecomkit-vuikhoe/ecomkit-vuikhoe.php');
function plugins_url(string $path,string $file): string{return 'https://example.test/plugin/'.$path;}
function wp_enqueue_script(mixed ...$a): void{}
function wp_enqueue_style(mixed ...$a): void{$GLOBALS['ui_styles'][]=$a;}
final class Ecomkit_Vuikhoe_Lazada_Config{public function safe_state(): array{return ['configured'=>true,'app_key'=>'SYNTHETIC','status'=>'READY','secret_status'=>'Stored securely'];}public function callback_url(): string{return 'https://example.test/wp-admin/admin-post.php?action=ecomkit_lazada_oauth_callback';}}
final class Ecomkit_Vuikhoe_Lazada_Token_Service{public function safe_connections(): array{return [['id'=>1,'shop'=>'SYNTHETIC-VN','identity_path'=>'country_user_info_list','status'=>'ACTIVE','lifecycle'=>'READY','access_expires_at'=>null,'refresh_expires_at'=>null]];}}
$batch=['id'=>31,'created_at'=>'2026-10-06','source_filename'=>'Synthetic-company-orders-long-filename.xlsx','source_type'=>'EXCEL','status'=>'WARNING','order_count'=>50,'source_metadata'=>'{}'];
$GLOBALS['ui_batches']=[$batch];$GLOBALS['ui_errors']=[['batch_id'=>31,'source'=>'EXCEL','stage'=>'IMPORT','sheet_name'=>'Orders','row_number'=>12,'order_code'=>'SYNTH-EXACT','error_code'=>'SYNTHETIC_REQUIRED_FIELD','friendly_message'=>'Synthetic missing source field','suggestion'=>'Check original Excel row and upload again','created_at'=>'2026-10-06']];
$columns=Ecomkit_Vuikhoe_Canonical_Columns::all();$values=array_fill_keys(array_column($columns,'key'),null);$values['raw_order_code']='987654321098765432109876543210';$values['order_date']='2026-10-06';$values['sales_channel']='LAZADA';$values['customer_name']='***';$values['address']='***';$values['amount_collected']='0';
$GLOBALS['ui_result']=['batch'=>$batch,'counts'=>['total'=>50,'SHOPEE'=>43,'LAZADA'=>7,'MATCHED'=>50,'NOT_FOUND_IN_SHOPEE'=>0,'DETAIL_MISSING'=>0,'ready'=>50,'warnings'=>2],'reconciliation'=>null,'columns'=>$columns,'rows'=>[['platform'=>'LAZADA','matching_status'=>'MATCHED','stale'=>false,'ready'=>true,'columns'=>$values,'rational'=>[],'formula_state'=>[]]]];
$GLOBALS['caps']=['edit_pages'=>true];$_GET=['batch_id'=>'31'];$GLOBALS['polling']=false;
$outputs=[];foreach(['dashboard','process','results','errors','history'] as $page){ob_start();$admin->{$page.'_page'}();$outputs[$page]=ob_get_clean();access_check(str_contains($outputs[$page],'ecomkit-page-header') && !str_contains($outputs[$page],'<style>'),'Shared header/scoped CSS missing '.$page);}
access_check(substr_count($outputs['results'],'<th>')===24 && str_contains($outputs['results'],'987654321098765432109876543210') && str_contains($outputs['results'],'>0</td>') && str_contains($outputs['results'],'&mdash;'),'24 columns/exact ID/null/zero changed');
$GLOBALS['ui_progress']=array_merge(array_fill_keys(['canonical_done','detail_done','detail_missing','error_count','income_done','income_total','items','lazada','matched','orders','payment_done','payment_failed','payment_fetched','payment_reused','payment_total','percent','reconcile_done','shopee','warning_count'],0),['orders'=>50,'items'=>53,'shopee'=>43,'lazada'=>7,'canonical_done'=>50,'matched'=>43,'percent'=>100,'status'=>'SUCCESS','terminal'=>true,'stalled'=>false,'stage_label'=>'Hoan tat','income_label'=>'Synthetic','updated_at'=>'2026-10-06']);
ob_start();$admin->results_page();$outputs['progress']=ob_get_clean();unset($GLOBALS['ui_progress']);
$GLOBALS['caps']=['manage_options'=>true];$_GET=[];
$data=['shopee_config'=>['environment'=>'production','partner_id'=>'SYNTHETIC'],'shopee_readiness'=>['ready'=>true],'partner_key_ui'=>['state'=>'not_configured','status'=>'SYNTHETIC','mask'=>'***'],'connections'=>[],'encryption_ready'=>true,'key_source'=>'WordPress Security Keys','callback_url'=>'https://example.test/callback'];
ob_start();require __DIR__.'/../ecomkit-vuikhoe/admin/views/marketplace.php';$outputs['marketplace']=ob_get_clean();
$runtime=['plugin_version'=>'0.7.35','db_schema_version'=>9,'php_version'=>'8.3','wordpress_version'=>'6.8','composer_autoload'=>true,'phpspreadsheet'=>true,'temp_available'=>true,'temp_writable'=>true,'upload_available'=>true,'upload_writable'=>true,'required_extensions'=>['zip','mbstring'],'missing_extensions'=>[]];
$data=['excel_runtime'=>$runtime,'database_runtime'=>['innodb_supported'=>true,'db_type'=>'MySQL','ready'=>true,'tables'=>array_fill_keys(['batches','orders','order_items','errors','marketplace_connections','sync_runs'],['engine'=>'InnoDB','transactional'=>true])],'orders_schema'=>['ready'=>true,'fields'=>[]],'runtime_test'=>null,'marketplace_security'=>['encryption'=>true,'key_source'=>'WordPress Security Keys','shopee'=>['ready'=>true],'callback_https'=>true]];
ob_start();require __DIR__.'/../ecomkit-vuikhoe/admin/views/settings.php';$outputs['settings']=ob_get_clean();
$GLOBALS['ui_styles']=[];$_GET=['page'=>'other-plugin'];$admin->enqueue_ui();access_check(!$GLOBALS['ui_styles'],'Styles leaked into other plugin');$_GET=['page'=>'ecomkit-vuikhoe-results'];$admin->enqueue_ui();access_check(count($GLOBALS['ui_styles'])===1 && $GLOBALS['ui_styles'][0][3]==='0.7.35','Stylesheet cache/scope');
$dir=getenv('ECOMKIT_UI_DIR');if($dir){if(!is_dir($dir))mkdir($dir,0777,true);$css=file_get_contents(__DIR__.'/../ecomkit-vuikhoe/assets/css/admin.css');foreach($outputs as $page=>$html){$html=preg_replace('~<script.*?</script>~s','',$html);file_put_contents($dir.'/'.$page.'.html','<!doctype html><meta charset="utf-8"><style>body{margin:0;background:#f0f0f1;font-family:system-ui}main{margin-left:160px;padding:16px 20px}aside{position:fixed;width:160px;height:100%;background:#1d2327;color:white;padding:20px;box-sizing:border-box}a{color:#1677c8}.button{cursor:pointer}'.$css.'</style><aside>WordPress<br><br>Ecomkit</aside><main>'.$html.'</main>');}}
echo "WP.6K.2 UI render: PASS (7 actual views, stylesheet scope/version, 24 columns, exact ID, NULL/zero; synthetic data, zero real calls)\n";
