<?php
/** WP.6E simulated one-upload orchestration: no business-stage button/action calls. */
declare(strict_types=1);
define( 'ABSPATH', __DIR__ . '/wordpress-placeholder/' ); define( 'ARRAY_A', 'ARRAY_A' );
function pipeline_check( bool $ok, string $message ): void { if ( ! $ok ) { throw new RuntimeException( $message ); } }
function wp_json_encode( mixed $value, int $flags = 0 ): string|false { return json_encode( $value, $flags ); }
function current_time( string $format, bool $utc = false ): string { return gmdate( 'Y-m-d H:i:s' ); }
function wp_timezone(): DateTimeZone { return new DateTimeZone( 'Asia/Bangkok' ); }
function sanitize_key( string $value ): string { return preg_replace( '/[^a-z0-9_\-]/', '', strtolower( $value ) ); }
$GLOBALS['options'] = array(); $GLOBALS['scheduled'] = array();
function add_option( string $name, mixed $value, string $deprecated = '', bool $autoload = false ): bool { if ( array_key_exists( $name, $GLOBALS['options'] ) ) { return false; } $GLOBALS['options'][ $name ] = $value; return true; }
function get_option( string $name, mixed $fallback = false ): mixed { return $GLOBALS['options'][ $name ] ?? $fallback; }
function delete_option( string $name ): bool { unset( $GLOBALS['options'][ $name ] ); return true; }
function wp_next_scheduled( string $hook, array $args ): int|false { foreach ( $GLOBALS['scheduled'] as $event ) { if ( $event['hook'] === $hook && $event['args'] === $args ) { return $event['time']; } } return false; }
function wp_schedule_single_event( int $time, string $hook, array $args ): bool { if ( ! empty( $GLOBALS['schedule_failure'] ) ) { return false; } $GLOBALS['scheduled'][] = compact( 'time', 'hook', 'args' ); return true; }
final class PipelineDb {
	public string $prefix = 'test_'; public array $batches = array(); public array $orders = array();
	public function prepare( string $query, mixed ...$args ): string { return json_encode( array( 'q' => $query, 'a' => $args ) ); }
	public function get_row( string $query, string $mode ): ?array { $parts = json_decode( $query, true ); return $this->batches[ (int) $parts['a'][0] ] ?? null; }
	public function get_results( string $query, string $mode ): array { $parts = json_decode( $query, true ); $batch_id = (int) $parts['a'][0]; return array_values( array_filter( $this->orders[ $batch_id ] ?? array(), static fn( array $order ): bool => 'SHOPEE' === $order['platform'] && 'MATCHED' === $order['matching_status'] ) ); }
	public function update( string $table, array $data, array $where ): int { $id = (int) $where['id']; pipeline_check( isset( $this->batches[ $id ] ) && array_keys( $data ) === array( 'source_metadata', 'updated_at' ), 'Pipeline touched unexpected DB fields.' ); $this->batches[ $id ] = array_merge( $this->batches[ $id ], $data ); return 1; }
}
$GLOBALS['wpdb'] = new PipelineDb();
require __DIR__ . '/../ecomkit-vuikhoe/includes/class-ecomkit-db.php';
require __DIR__ . '/../ecomkit-vuikhoe/includes/class-ecomkit-shopee-income-service.php';
require __DIR__ . '/../ecomkit-vuikhoe/includes/class-ecomkit-auto-pipeline.php';
$db = $GLOBALS['wpdb'];
function create_batch( int $id, int $shopee, int $lazada ): void { global $db; $db->batches[ $id ] = array( 'id' => $id, 'source_type' => 'EXCEL', 'status' => 'SUCCESS', 'order_count' => $shopee + $lazada, 'source_metadata' => json_encode( array( 'platform_counts' => array( 'SHOPEE' => $shopee, 'LAZADA' => $lazada ), 'item_rows' => 18 ) ) ); $db->orders[ $id ] = array(); for ( $i = 1; $i <= $shopee + $lazada; $i++ ) { $db->orders[ $id ][] = array( 'id' => $i, 'platform' => $i <= $shopee ? 'SHOPEE' : 'LAZADA', 'matching_status' => '', 'marketplace_order_id' => sprintf( 'TEST-SHP-%03d', $i ), 'eshop_order_code' => 'ĐH' . $i, 'order_date' => '2026-10-01 00:00:00', 'payment_normalized_data' => null ); } }
function drain( Ecomkit_Vuikhoe_Auto_Pipeline $pipeline, int $limit = 120 ): void { $last = 0; for ( $i = 0; $i < $limit && $GLOBALS['scheduled']; $i++ ) { $event = array_shift( $GLOBALS['scheduled'] ); pipeline_check( Ecomkit_Vuikhoe_Auto_Pipeline::HOOK === $event['hook'], 'Unexpected scheduled event.' ); $batch_id = (int) $event['args'][0]; $pipeline->run_one( $batch_id ); $state = $pipeline->state( $batch_id ); $percent = Ecomkit_Vuikhoe_Auto_Pipeline::progress( $state )['percent']; pipeline_check( $percent >= $last, 'Persisted progress moved backward during one run.' ); $last = $percent; } pipeline_check( ! $GLOBALS['scheduled'], 'Pipeline did not reach terminal state within bound.' ); }
create_batch( 8, 4, 4 ); $calls = array( 'reconcile' => 0, 'payment' => 0, 'income_page' => 0, 'materialize' => 0 );
$operations = array(
	'ready_connections' => static fn(): array => array( array( 'id' => 9 ) ),
	'reconcile' => static function ( int $batch_id, int $connection_id ) use ( &$calls, $db ): array { $calls['reconcile']++; pipeline_check( 9 === $connection_id, 'Wrong shop.' ); foreach ( $db->orders[ $batch_id ] as &$order ) { if ( 'SHOPEE' === $order['platform'] ) { $order['matching_status'] = 'MATCHED'; } } unset( $order ); return array( 'status' => 'SUCCESS', 'matched_count' => 4 ); },
	'payment' => static function ( int $batch_id, int $order_id ) use ( &$calls, $db ): void { $calls['payment']++; if ( 4 === $order_id ) { throw new RuntimeException( 'SHOPEE_PAYMENT_UNAVAILABLE' ); } foreach ( $db->orders[ $batch_id ] as &$order ) { if ( $order_id === $order['id'] ) { $order['payment_normalized_data'] = json_encode( array( 'marketplaceOrderId' => $order['marketplace_order_id'], 'commissionFee' => 1000 ) ); } } unset( $order ); },
	'income_page' => static function ( int $connection_id, array $query, string $cursor ) use ( &$calls ): array { $calls['income_page']++; pipeline_check( 9 === $connection_id && '' === $cursor && in_array( $query['bucket'], array( 'PENDING', 'RELEASED' ), true ), 'Income query repeated or wrong.' ); return array( 'classification' => 'SHOPEE_INCOME_EMPTY', 'records' => array(), 'next_cursor' => '', 'request_id' => 'synthetic' ); },
	'materialize' => static function ( int $batch_id ) use ( &$calls, $db ): array { $calls['materialize']++; pipeline_check( 8 === count( $db->orders[ $batch_id ] ), 'Business rows changed.' ); return array( 'rows' => count( $db->orders[ $batch_id ] ) ); },
);
$pipeline = new Ecomkit_Vuikhoe_Auto_Pipeline( $operations ); $pipeline->start( 8 ); drain( $pipeline ); $state = $pipeline->state( 8 );
pipeline_check( 'WARNING' === $state['status'] && 'RESULT_READY' === $state['stage'] && 8 === $state['counts']['canonical_rows'] && 4 === $state['counts']['shopee_matched'] && 3 === $state['counts']['payment_fetched'] && 1 === $state['counts']['payment_failed'] && 1 === $calls['reconcile'] && 4 === $calls['payment'] && 1 === $calls['materialize'] && $calls['income_page'] <= 7, 'One-upload partial-Payment pipeline failed.' );
pipeline_check( 100 === Ecomkit_Vuikhoe_Auto_Pipeline::progress( $state )['percent'], 'Soft Payment warning did not finish at 100%.' );
pipeline_check( null === $db->orders[8][3]['payment_normalized_data'] && 'ĐH4' === $db->orders[8][3]['eshop_order_code'], 'Failure fabricated fee or changed eShop identity.' );
create_batch( 12, 4, 4 ); $shared_calls = 0; $stored_income = 0;
$happy_ops = array(
	'ready_connections' => static fn(): array => array( array( 'id' => 9 ) ),
	'reconcile' => static function ( int $batch_id ) use ( $db ): array { foreach ( $db->orders[ $batch_id ] as &$order ) { if ( 'SHOPEE' === $order['platform'] ) { $order['matching_status'] = 'MATCHED'; } } unset( $order ); return array( 'status' => 'SUCCESS', 'matched_count' => 4 ); },
	'payment' => static function ( int $batch_id, int $order_id ) use ( $db ): void { foreach ( $db->orders[ $batch_id ] as &$order ) { if ( $order_id === $order['id'] ) { $order['payment_normalized_data'] = json_encode( array( 'marketplaceOrderId' => $order['marketplace_order_id'], 'commissionFee' => 1000 ) ); } } unset( $order ); },
	'income_page' => static function ( int $connection_id, array $query, string $cursor ) use ( &$shared_calls ): array { $shared_calls++; return array( 'classification' => 'SUCCESS', 'records' => 'PENDING' === $query['bucket'] ? array( array( 'order_sn' => 'TEST-SHP-001', 'estimated_escrow_amount' => 218940 ), array( 'order_sn' => 'TEST-SHP-002', 'estimated_escrow_amount' => 0 ), array( 'order_sn' => 'test-shp-003' ) ) : array(), 'next_cursor' => '', 'request_id' => 'shared' ); },
	'income_store' => static function ( int $batch_id, array $order, array $item, array $query ) use ( $db, &$stored_income ): void { $stored_income++; foreach ( $db->orders[ $batch_id ] as &$row ) { if ( $row['id'] === $order['id'] ) { $row['income_normalized_data'] = json_encode( array( 'marketplaceOrderId' => $item['order_sn'], 'incomeBucket' => $query['bucket'], 'estimatedEscrowAmount' => $item['estimated_escrow_amount'] ) ); } } unset( $row ); },
	'materialize' => static function ( int $batch_id ) use ( $db ): array { pipeline_check( 8 === count( $db->orders[ $batch_id ] ), 'Happy path changed Order count.' ); return array( 'rows' => 8 ); },
);
$happy = new Ecomkit_Vuikhoe_Auto_Pipeline( $happy_ops ); $happy->start( 12 ); drain( $happy ); $happy_state = $happy->state( 12 ); pipeline_check( 'SUCCESS' === $happy_state['status'] && 'RESULT_READY' === $happy_state['stage'] && 4 === $happy_state['counts']['payment_fetched'] && 2 === $happy_state['counts']['income_matched'] && 2 === $stored_income && $shared_calls <= 7 && 8 === $happy_state['counts']['canonical_rows'], 'One-upload 8/4/4 happy path or shared Income lookup failed.' );
create_batch( 14, 4, 4 ); $window_calls = array(); $window_ops = $happy_ops; $window_ops['reconcile'] = static function ( int $batch_id, int $connection_id, array $limits ) use ( &$window_calls, $db ): array { $offset = $limits['window_offset']; $window_calls[] = $offset; pipeline_check( 1 === $limits['max_windows'] && 2 === $limits['max_pages'] && 1 === $limits['max_detail_batches'], 'Reconciliation call was not bounded.' ); foreach ( $db->orders[ $batch_id ] as &$order ) { if ( 'SHOPEE' === $order['platform'] && $order['id'] > $offset * 2 && $order['id'] <= ( $offset + 1 ) * 2 ) { $order['matching_status'] = 'MATCHED'; } } unset( $order ); return array( 'status' => 'SUCCESS', 'matched_count' => ( $offset + 1 ) * 2, 'next_window_offset' => $offset + 1, 'total_windows' => 2 ); }; $window_ops['income_page'] = static fn(): array => array( 'classification' => 'SHOPEE_INCOME_EMPTY', 'records' => array(), 'next_cursor' => '', 'request_id' => 'safe' ); $multi = new Ecomkit_Vuikhoe_Auto_Pipeline( $window_ops ); $multi->start( 14 ); drain( $multi ); pipeline_check( array( 0, 1 ) === $window_calls && 4 === $multi->state( 14 )['counts']['shopee_matched'] && 8 === $multi->state( 14 )['counts']['canonical_rows'], 'Reconciliation windows did not resume automatically.' );
$before = $calls; $pipeline->start( 8 ); pipeline_check( $before === $calls && ! $GLOBALS['scheduled'], 'Completed pipeline restarted unexpectedly.' );
create_batch( 11, 4, 4 ); $resume_pipeline = new Ecomkit_Vuikhoe_Auto_Pipeline( $operations ); $resume_pipeline->start( 11 );
for ( $i = 0; $i < 10 && $GLOBALS['scheduled']; $i++ ) { $event = array_shift( $GLOBALS['scheduled'] ); $resume_pipeline->run_one( (int) $event['args'][0] ); if ( 2 === (int) ( $resume_pipeline->state( 11 )['payment_index'] ?? 0 ) ) { break; } }
pipeline_check( 2 === $resume_pipeline->state( 11 )['counts']['payment_fetched'], 'Payment interruption fixture did not reach 2/4.' );
$GLOBALS['scheduled'] = array(); $payments_before_resume = $calls['payment']; $resumed = new Ecomkit_Vuikhoe_Auto_Pipeline( $operations ); $resumed->start( 11 ); drain( $resumed ); pipeline_check( 2 === $calls['payment'] - $payments_before_resume && 8 === $resumed->state( 11 )['counts']['canonical_rows'], 'Resume repeated completed Payment calls or missed Result.' );
create_batch( 9, 0, 4 ); $lazada_calls = 0; $lazada_pipeline = new Ecomkit_Vuikhoe_Auto_Pipeline( array( 'ready_connections' => static function () use ( &$lazada_calls ): array { $lazada_calls++; return array(); }, 'materialize' => static fn(): array => array( 'rows' => 4 ) ) ); $lazada_pipeline->start( 9 ); drain( $lazada_pipeline ); pipeline_check( 0 === $lazada_calls && 4 === $lazada_pipeline->state( 9 )['counts']['canonical_rows'], 'Lazada-only Batch called Shopee or missed Result.' );
create_batch( 10, 1, 0 ); $no_shop = new Ecomkit_Vuikhoe_Auto_Pipeline( array( 'ready_connections' => static fn(): array => array(), 'materialize' => static fn(): array => array( 'rows' => 1 ) ) ); $no_shop->start( 10 ); drain( $no_shop ); pipeline_check( 'WARNING' === $no_shop->state( 10 )['status'] && 'RESULT_READY' === $no_shop->state( 10 )['stage'] && in_array( 'SHOPEE_CONNECTION_NOT_READY', $no_shop->state( 10 )['warnings'], true ), 'No-connection path lost Excel result.' );
create_batch( 16, 1, 0 ); $many_shops = new Ecomkit_Vuikhoe_Auto_Pipeline( array( 'ready_connections' => static fn(): array => array( array( 'id' => 9 ), array( 'id' => 10 ) ), 'materialize' => static fn(): array => array( 'rows' => 1 ) ) ); $many_shops->start( 16 ); drain( $many_shops ); pipeline_check( 'WARNING' === $many_shops->state( 16 )['status'] && in_array( 'SHOP_SELECTION_REQUIRED', $many_shops->state( 16 )['warnings'], true ), 'Multiple shops were chosen arbitrarily.' );
create_batch( 13, 4, 4 ); $income_error_ops = $happy_ops; $income_error_ops['income_page'] = static function (): array { throw new RuntimeException( 'SHOPEE_INCOME_NETWORK_ERROR' ); }; $income_error = new Ecomkit_Vuikhoe_Auto_Pipeline( $income_error_ops ); $income_error->start( 13 ); drain( $income_error ); pipeline_check( 'WARNING' === $income_error->state( 13 )['status'] && 'WARNING' === $income_error->state( 13 )['income_status'] && 8 === $income_error->state( 13 )['counts']['canonical_rows'], 'Income provider error blocked Result.' );
create_batch( 17, 4, 4 ); $cursor_calls = array(); $cursor_ops = $happy_ops; $cursor_ops['income_page'] = static function ( int $connection_id, array $query, string $cursor ) use ( &$cursor_calls ): array { $cursor_calls[] = $cursor; return array( 'classification' => 'SUCCESS', 'records' => 'next' === $cursor ? array( array( 'order_sn' => 'TEST-SHP-003', 'estimated_escrow_amount' => 0 ) ) : array(), 'next_cursor' => '' === $cursor && 'PENDING' === $query['bucket'] ? 'next' : '', 'request_id' => 'cursor-safe' ); }; $cursor_count = 0; $cursor_ops['income_store'] = static function () use ( &$cursor_count ): void { $cursor_count++; }; $cursor_pipeline = new Ecomkit_Vuikhoe_Auto_Pipeline( $cursor_ops ); $cursor_pipeline->start( 17 ); drain( $cursor_pipeline ); pipeline_check( array( '', 'next' ) === array_slice( $cursor_calls, 0, 2 ) && 1 === $cursor_count && 8 === $cursor_pipeline->state( 17 )['counts']['canonical_rows'], 'Income cursor did not resume exactly or block-free.' );
create_batch( 15, 0, 2 ); $GLOBALS['schedule_failure'] = true; $schedule_fallback = new Ecomkit_Vuikhoe_Auto_Pipeline( array( 'materialize' => static fn(): array => array( 'rows' => 2 ) ) ); $schedule_fallback->start( 15 ); pipeline_check( 'WARNING' === $schedule_fallback->state( 15 )['status'] && 2 === $schedule_fallback->state( 15 )['counts']['canonical_rows'] && ! $GLOBALS['scheduled'], 'Cron scheduling failure lost Excel Result.' ); $GLOBALS['schedule_failure'] = false;
create_batch( 18, 0, 2 ); $short_result = new Ecomkit_Vuikhoe_Auto_Pipeline( array( 'materialize' => static fn(): array => array( 'rows' => 1 ) ) ); $short_result->start( 18 ); drain( $short_result ); pipeline_check( 'ERROR' === $short_result->state( 18 )['status'] && Ecomkit_Vuikhoe_Auto_Pipeline::progress( $short_result->state( 18 ) )['percent'] < 100, 'Incomplete canonical row count falsely completed.' );
$admin_source = file_get_contents( __DIR__ . '/../ecomkit-vuikhoe/includes/class-ecomkit-admin.php' ); pipeline_check( str_contains( $admin_source, '->import_upload( $file' ) && str_contains( $admin_source, '->start( $batch_id )' ), 'Upload does not trigger pipeline.' );
$result_view = file_get_contents( __DIR__ . '/../ecomkit-vuikhoe/admin/views/results.php' ); pipeline_check( ! str_contains( $result_view, 'UI: Nền tảng / Matching / Cảnh báo' ) && str_contains( $result_view, "foreach ( \$result['columns'] as \$column )" ), 'Result table adds a noncanonical column.' );
pipeline_check( str_contains( $result_view, '<details><summary>' ) && str_contains( $result_view, 'Công cụ quản trị nâng cao' ) && str_contains( $result_view, 'Chỉ dùng khi cần kiểm tra kỹ thuật' ), 'Technical actions are prominent in normal Result view.' );
create_batch( 19, 0, 1 ); $gap_pipeline = new Ecomkit_Vuikhoe_Auto_Pipeline( array( 'materialize' => static fn(): array => array( 'rows' => 1, 'service_fee_source_gaps' => 1 ) ) ); $gap_pipeline->start( 19 ); drain( $gap_pipeline ); $gap_state = $gap_pipeline->state( 19 ); pipeline_check( 'WARNING' === $gap_state['status'] && 100 === Ecomkit_Vuikhoe_Auto_Pipeline::progress( $gap_state )['percent'] && in_array( 'SERVICE_FEE_SOURCE_GAP', $gap_state['warnings'], true ), 'Service fee source gap blocked completion or was not explained.' );
create_batch( 25, 2, 1 ); $zero_calls = array( 'payment' => 0, 'income' => 0 );
$zero_pipeline = new Ecomkit_Vuikhoe_Auto_Pipeline( array(
	'ready_connections' => static fn(): array => array( array( 'id' => 9 ) ),
	'reconcile' => static fn(): array => array( 'status' => 'WARNING', 'classification' => 'SHOPEE_RECON_PROVIDER_WINDOW_EMPTY', 'matched_count' => 0, 'missing_count' => 2, 'detail_count' => 0, 'total_windows' => 1, 'next_window_offset' => 1 ),
	'payment' => static function () use ( &$zero_calls ): void { $zero_calls['payment']++; },
	'income_page' => static function () use ( &$zero_calls ): array { $zero_calls['income']++; return array(); },
	'materialize' => static fn(): array => array( 'rows' => 3 ),
) );
$zero_pipeline->start( 25 ); drain( $zero_pipeline ); $zero_state = $zero_pipeline->state( 25 );
pipeline_check( 'WARNING' === $zero_state['status'] && 100 === Ecomkit_Vuikhoe_Auto_Pipeline::progress( $zero_state )['percent'] && 3 === $zero_state['counts']['canonical_rows'] && 0 === $zero_state['counts']['payment_total'] && array( 'payment' => 0, 'income' => 0 ) === $zero_calls && in_array( 'SHOPEE_RECON_PROVIDER_WINDOW_EMPTY', $zero_state['warnings'], true ), 'Zero-match pipeline called downstream provider or hid 3-row Result.' );
create_batch( 26, 11, 0 ); $recon_steps = 0; $detail_after_resume = 0;
$resume_ops = array(
	'ready_connections' => static fn(): array => array( array( 'id' => 9 ) ),
	'reconcile' => static function ( int $batch_id, int $connection_id, array $limits ) use ( &$recon_steps, $db ): array {
		$recon_steps++;
		pipeline_check( 9 === $connection_id && 0 === $limits['window_offset'], 'Reconciliation changed shop/window while paging.' );
		if ( $recon_steps < 3 ) { pipeline_check( $recon_steps - 1 === (int) ( $limits['continuation']['page_count'] ?? 0 ), 'Persisted cursor/page state was lost between cron events.' ); return array( 'status' => 'PROCESSING', 'total_windows' => 1, 'next_window_offset' => 0, 'continuation' => array( 'cursor' => 'page-' . $recon_steps, 'provider_ids' => array_fill_keys( range( 1, $recon_steps * 5 ), true ), 'page_count' => $recon_steps ) ); }
		pipeline_check( 2 === (int) ( $limits['continuation']['page_count'] ?? 0 ) && 10 === count( $limits['continuation']['provider_ids'] ), 'Third cron invocation did not receive all prior IDs.' );
		foreach ( $db->orders[ $batch_id ] as &$order ) { $order['matching_status'] = 'MATCHED'; } unset( $order );
		return array( 'status' => 'SUCCESS', 'matched_count' => 11, 'missing_count' => 0, 'detail_count' => 11, 'total_windows' => 1, 'next_window_offset' => 1 );
	},
	'payment' => static function ( int $batch_id, int $order_id ) use ( &$detail_after_resume ): void { $detail_after_resume++; },
	'income_page' => static fn(): array => array( 'classification' => 'SHOPEE_INCOME_EMPTY', 'records' => array(), 'next_cursor' => '', 'request_id' => 'safe' ),
	'materialize' => static fn(): array => array( 'rows' => 11 ),
);
$multi_cron = new Ecomkit_Vuikhoe_Auto_Pipeline( $resume_ops ); $multi_cron->start( 26 ); drain( $multi_cron ); $multi_state = $multi_cron->state( 26 );
pipeline_check( 3 === $recon_steps && 11 === $multi_state['counts']['shopee_matched'] && 11 === $multi_state['counts']['reconcile_checked'] && 11 === $multi_state['counts']['canonical_rows'] && 11 === $detail_after_resume && 100 === Ecomkit_Vuikhoe_Auto_Pipeline::progress( $multi_state )['percent'], 'Multi-cron 5+5+1 continuation did not run downstream 11-order pipeline.' );
$unresolved = $multi_state; $unresolved['status'] = 'WARNING'; $unresolved['counts']['reconcile_checked'] = 0; $unresolved['counts']['shopee_matched'] = 0;
pipeline_check( 0 === Ecomkit_Vuikhoe_Auto_Pipeline::progress( $unresolved )['reconcile_done'], 'Terminal warning falsely presented 11/11 as checked with matched=missing=0.' );
echo "WP.6E one-upload pipeline checks passed.\n";
