<?php
/** WP.6E simulated one-upload orchestration: no business-stage button/action calls. */
declare(strict_types=1);
define( 'ABSPATH', __DIR__ . '/wordpress-placeholder/' ); define( 'ARRAY_A', 'ARRAY_A' );
function pipeline_check( bool $ok, string $message ): void { if ( ! $ok ) { throw new RuntimeException( $message ); } }
function wp_json_encode( mixed $value, int $flags = 0 ): string|false { return json_encode( $value, $flags ); }
function current_time( string $format, bool $utc = false ): string { return gmdate( 'Y-m-d H:i:s' ); }
function wp_timezone(): DateTimeZone { return new DateTimeZone( 'Asia/Bangkok' ); }
function sanitize_key( string $value ): string { return preg_replace( '/[^a-z0-9_\-]/', '', strtolower( $value ) ); }
$GLOBALS['options'] = array(); $GLOBALS['scheduled'] = array();
function add_option( string $name, mixed $value, string $deprecated = '', bool $autoload = false ): bool { if ( array_key_exists( $name, $GLOBALS['options'] ) ) { return false; } $GLOBALS['options'][ $name ] = $value; return true; }
function get_option( string $name, mixed $fallback = false ): mixed { return $GLOBALS['options'][ $name ] ?? $fallback; }
function delete_option( string $name ): bool { unset( $GLOBALS['options'][ $name ] ); return true; }
function wp_next_scheduled( string $hook, array $args ): int|false { foreach ( $GLOBALS['scheduled'] as $event ) { if ( $event['hook'] === $hook && $event['args'] === $args ) { return $event['time']; } } return false; }
function wp_schedule_single_event( int $time, string $hook, array $args ): bool { if ( ! empty( $GLOBALS['schedule_failure'] ) ) { return false; } $GLOBALS['scheduled'][] = compact( 'time', 'hook', 'args' ); return true; }
final class PipelineDb {
	public string $prefix = 'test_'; public array $batches = array(); public array $orders = array();
	public function prepare( string $query, mixed ...$args ): string { return json_encode( array( 'q' => $query, 'a' => $args ) ); }
	public function get_row( string $query, string $mode ): ?array { $parts = json_decode( $query, true ); return $this->batches[ (int) $parts['a'][0] ] ?? null; }
	public function get_results( string $query, string $mode ): array { $parts = json_decode( $query, true ); $batch_id = (int) $parts['a'][0]; return array_values( array_filter( $this->orders[ $batch_id ] ?? array(), static fn( array $order ): bool => 'SHOPEE' === $order['platform'] && 'MATCHED' === $order['matching_status'] ) ); }
	public function update( string $table, array $data, array $where ): int { $id = (int) $where['id']; pipeline_check( isset( $this->batches[ $id ] ) && array_keys( $data ) === array( 'source_metadata', 'updated_at' ), 'Pipeline touched unexpected DB fields.' ); $this->batches[ $id ] = array_merge( $this->batches[ $id ], $data ); return 1; }
}
$GLOBALS['wpdb'] = new PipelineDb();
require __DIR__ . '/../ecomkit-vuikhoe/includes/class-ecomkit-db.php';
require __DIR__ . '/../ecomkit-vuikhoe/includes/class-ecomkit-shopee-income-service.php';
require __DIR__ . '/../ecomkit-vuikhoe/includes/class-ecomkit-auto-pipeline.php';
$db = $GLOBALS['wpdb'];
function create_batch( int $id, int $shopee, int $lazada ): void { global $db; $db->batches[ $id ] = array( 'id' => $id, 'source_type' => 'EXCEL', 'status' => 'SUCCESS', 'order_count' => $shopee + $lazada, 'source_metadata' => json_encode( array( 'platform_counts' => array( 'SHOPEE' => $shopee, 'LAZADA' => $lazada ), 'item_rows' => 18 ) ) ); $db->orders[ $id ] = array(); for ( $i = 1; $i <= $shopee + $lazada; $i++ ) { $db->orders[ $id ][] = array( 'id' => $i, 'platform' => $i <= $shopee ? 'SHOPEE' : 'LAZADA', 'matching_status' => '', 'marketplace_order_id' => sprintf( 'TEST-SHP-%03d', $i ), 'eshop_order_code' => 'ĐH' . $i, 'order_date' => '2026-10-01 00:00:00', 'payment_normalized_data' => null ); } }
function drain( Ecomkit_Vuikhoe_Auto_Pipeline $pipeline, int $limit = 120 ): void { $last = 0; for ( $i = 0; $i < $limit && $GLOBALS['scheduled']; $i++ ) { $event = array_shift( $GLOBALS['scheduled'] ); pipeline_check( Ecomkit_Vuikhoe_Auto_Pipeline::HOOK === $event['hook'], 'Unexpected scheduled event.' ); $batch_id = (int) $event['args'][0]; $pipeline->run_one( $batch_id ); $state = $pipeline->state( $batch_id ); $percent = Ecomkit_Vuikhoe_Auto_Pipeline::progress( $state )['percent']; pipeline_check( $percent >= $last, 'Persisted progress moved backward during one run.' ); $last = $percent; } pipeline_check( ! $GLOBALS['scheduled'], 'Pipeline did not reach terminal state within bound.' ); }
create_batch( 8, 4, 4 ); $calls = array( 'reconcile' => 0, 'payment' => 0, 'income_page' => 0, 'materialize' => 0 );
$operations = array(
	'ready_connections' => static fn(): array => array( array( 'id' => 9 ) ),
	'reconcile' => static function ( int $batch_id, int $connection_id ) use ( &$calls, $db ): array { $calls['reconcile']++; pipeline_check( 9 === $connection_id, 'Wrong shop.' ); foreach ( $db->orders[ $batch_id ] as &$order ) { if ( 'SHOPEE' === $order['platform'] ) { $order['matching_status'] = 'MATCHED'; } } unset( $order ); return array( 'status' => 'SUCCESS', 'matched_count' => 4 ); },
	'payment' => static function ( int $batch_id, int $order_id ) use ( &$calls, $db ): void { $calls['payment']++; if ( 4 === $order_id ) { throw new RuntimeException( 'SHOPEE_PAYMENT_UNAVAILABLE' ); } foreach ( $db->orders[ $batch_id ] as &$order ) { if ( $order_id === $order['id'] ) { $order['payment_normalized_data'] = json_encode( array( 'marketplaceOrderId' => $order['marketplace_order_id'], 'commissionFee' => 1000 ) ); } } unset( $order ); },
	'income_page' => static function ( int $connection_id, array $query, string $cursor ) use ( &$calls ): array { $calls['income_page']++; pipeline_check( 9 === $connection_id && '' === $cursor && in_array( $query['bucket'], array( 'PENDING', 'RELEASED' ), true ), 'Income query repeated or wrong.' ); return array( 'classification' => 'SHOPEE_INCOME_EMPTY', 'records' => array(), 'next_cursor' => '', 'request_id' => 'synthetic' ); },
	'materialize' => static function ( int $batch_id ) use ( &$calls, $db ): array { $calls['materialize']++; pipeline_check( 8 === count( $db->orders[ $batch_id ] ), 'Business rows changed.' ); return array( 'rows' => count( $db->orders[ $batch_id ] ) ); },
);
$pipeline = new Ecomkit_Vuikhoe_Auto_Pipeline( $operations ); $pipeline->start( 8 ); drain( $pipeline ); $state = $pipeline->state( 8 );
pipeline_check( 'WARNING' === $state['status'] && 'RESULT_READY' === $state['stage'] && 8 === $state['counts']['canonical_rows'] && 4 === $state['counts']['shopee_matched'] && 3 === $state['counts']['payment_fetched'] && 1 === $state['counts']['payment_failed'] && 1 === $calls['reconcile'] && 4 === $calls['payment'] && 1 === $calls['materialize'] && $calls['income_page'] <= 7, 'One-upload partial-Payment pipeline failed.' );
pipeline_check( 100 === Ecomkit_Vuikhoe_Auto_Pipeline::progress( $state )['percent'], 'Soft Payment warning did not finish at 100%.' );
pipeline_check( null === $db->orders[8][3]['payment_normalized_data'] && 'ĐH4' === $db->orders[8][3]['eshop_order_code'], 'Failure fabricated fee or changed eShop identity.' );
create_batch( 35, 1, 0 ); $resume_completed_ops = array( 'ready_connections' => static fn(): array => array( array( 'id' => 9 ) ), 'reconcile' => static fn(): array => array( 'status' => 'SUCCESS', 'matched_count' => 0, 'missing_count' => 1, 'total_windows' => 1, 'next_window_offset' => 1 ), 'materialize' => static fn(): array => array( 'rows' => 1 ) ); $resume_completed = new Ecomkit_Vuikhoe_Auto_Pipeline( $resume_completed_ops ); $resume_completed->start( 35 ); drain( $resume_completed ); $meta = json_decode( $db->batches[35]['source_metadata'], true ); $meta['shopee_reconciliation'] = array( 'status' => 'WARNING', 'matched_count' => 0, 'detail_count' => 0 ); $db->batches[35]['source_metadata'] = json_encode( $meta ); $resume_completed->start( 35, true ); drain( $resume_completed ); pipeline_check( 'RESULT_READY' === $resume_completed->state( 35 )['stage'] && 100 === Ecomkit_Vuikhoe_Auto_Pipeline::progress( $resume_completed->state( 35 ) )['percent'], 'Resume after complete reconciliation lost window/count evidence.' );
create_batch( 12, 4, 4 ); $shared_calls = 0; $stored_income = 0;
$happy_ops = array(
	'ready_connections' => static fn(): array => array( array( 'id' => 9 ) ),
	'reconcile' => static function ( int $batch_id ) use ( $db ): array { foreach ( $db->orders[ $batch_id ] as &$order ) { if ( 'SHOPEE' === $order['platform'] ) { $order['matching_status'] = 'MATCHED'; } } unset( $order ); return array( 'status' => 'SUCCESS', 'matched_count' => 4 ); },
	'payment' => static function ( int $batch_id, int $order_id ) use ( $db ): void { foreach ( $db->orders[ $batch_id ] as &$order ) { if ( $order_id === $order['id'] ) { $order['payment_normalized_data'] = json_encode( array( 'marketplaceOrderId' => $order['marketplace_order_id'], 'commissionFee' => 1000 ) ); } } unset( $order ); },
	'income_page' => static function ( int $connection_id, array $query, string $cursor ) use ( &$shared_calls ): array { $shared_calls++; return array( 'classification' => 'SUCCESS', 'records' => 'PENDING' === $query['bucket'] ? array( array( 'order_sn' => 'TEST-SHP-001', 'estimated_escrow_amount' => 218940 ), array( 'order_sn' => 'TEST-SHP-002', 'estimated_escrow_amount' => 0 ), array( 'order_sn' => 'test-shp-003' ) ) : array(), 'next_cursor' => '', 'request_id' => 'shared' ); },
	'income_store' => static function ( int $batch_id, array $order, array $item, array $query ) use ( $db, &$stored_income ): void { $stored_income++; foreach ( $db->orders[ $batch_id ] as &$row ) { if ( $row['id'] === $order['id'] ) { $row['income_normalized_data'] = json_encode( array( 'marketplaceOrderId' => $item['order_sn'], 'incomeBucket' => $query['bucket'], 'estimatedEscrowAmount' => $item['estimated_escrow_amount'] ) ); } } unset( $row ); },
	'materialize' => static function ( int $batch_id ) use ( $db ): array { pipeline_check( 8 === count( $db->orders[ $batch_id ] ), 'Happy path changed Order count.' ); return array( 'rows' => 8 ); },
);
$happy = new Ecomkit_Vuikhoe_Auto_Pipeline( $happy_ops ); $happy->start( 12 ); drain( $happy ); $happy_state = $happy->state( 12 ); pipeline_check( 'SUCCESS' === $happy_state['status'] && 'RESULT_READY' === $happy_state['stage'] && 4 === $happy_state['counts']['payment_fetched'] && 2 === $happy_state['counts']['income_matched'] && 2 === $stored_income && $shared_calls <= 7 && 8 === $happy_state['counts']['canonical_rows'], 'One-upload 8/4/4 happy path or shared Income lookup failed.' );
create_batch( 14, 4, 4 ); $window_calls = array(); $window_ops = $happy_ops; $window_ops['reconcile'] = static function ( int $batch_id, int $connection_id, array $limits ) use ( &$window_calls, $db ): array { $offset = $limits['window_offset']; $window_calls[] = $offset; pipeline_check( 1 === $limits['max_windows'] && 2 === $limits['max_pages'] && 1 === $limits['max_detail_batches'], 'Reconciliation call was not bounded.' ); foreach ( $db->orders[ $batch_id ] as &$order ) { if ( 'SHOPEE' === $order['platform'] && $order['id'] > $offset * 2 && $order['id'] <= ( $offset + 1 ) * 2 ) { $order['matching_status'] = 'MATCHED'; } } unset( $order ); return array( 'status' => 'SUCCESS', 'matched_count' => ( $offset + 1 ) * 2, 'next_window_offset' => $offset + 1, 'total_windows' => 2 ); }; $window_ops['income_page'] = static fn(): array => array( 'classification' => 'SHOPEE_INCOME_EMPTY', 'records' => array(), 'next_cursor' => '', 'request_id' => 'safe' ); $multi = new Ecomkit_Vuikhoe_Auto_Pipeline( $window_ops ); $multi->start( 14 ); drain( $multi ); pipeline_check( array( 0, 1 ) === $window_calls && 4 === $multi->state( 14 )['counts']['shopee_matched'] && 8 === $multi->state( 14 )['counts']['canonical_rows'], 'Reconciliation windows did not resume automatically.' );
$before = $calls; $pipeline->start( 8 ); pipeline_check( $before === $calls && ! $GLOBALS['scheduled'], 'Completed pipeline restarted unexpectedly.' );
create_batch( 11, 4, 4 ); $resume_pipeline = new Ecomkit_Vuikhoe_Auto_Pipeline( $operations ); $resume_pipeline->start( 11 );
for ( $i = 0; $i < 10 && $GLOBALS['scheduled']; $i++ ) { $event = array_shift( $GLOBALS['scheduled'] ); $resume_pipeline->run_one( (int) $event['args'][0] ); if ( 2 === (int) ( $resume_pipeline->state( 11 )['payment_index'] ?? 0 ) ) { break; } }
pipeline_check( 2 === $resume_pipeline->state( 11 )['counts']['payment_fetched'], 'Payment interruption fixture did not reach 2/4.' );
$GLOBALS['scheduled'] = array(); $payments_before_resume = $calls['payment']; $resumed = new Ecomkit_Vuikhoe_Auto_Pipeline( $operations ); $resumed->start( 11 ); drain( $resumed ); pipeline_check( 2 === $calls['payment'] - $payments_before_resume && 8 === $resumed->state( 11 )['counts']['canonical_rows'], 'Resume repeated completed Payment calls or missed Result.' );
create_batch( 9, 0, 4 ); $lazada_calls = 0; $lazada_pipeline = new Ecomkit_Vuikhoe_Auto_Pipeline( array( 'ready_connections' => static function () use ( &$lazada_calls ): array { $lazada_calls++; return array(); }, 'materialize' => static fn(): array => array( 'rows' => 4 ) ) ); $lazada_pipeline->start( 9 ); drain( $lazada_pipeline ); pipeline_check( 0 === $lazada_calls && 4 === $lazada_pipeline->state( 9 )['counts']['canonical_rows'], 'Lazada-only Batch called Shopee or missed Result.' );
create_batch( 10, 1, 0 ); $no_shop = new Ecomkit_Vuikhoe_Auto_Pipeline( array( 'ready_connections' => static fn(): array => array(), 'materialize' => static fn(): array => array( 'rows' => 1 ) ) ); $no_shop->start( 10 ); drain( $no_shop ); pipeline_check( 'WARNING' === $no_shop->state( 10 )['status'] && 'RESULT_READY' === $no_shop->state( 10 )['stage'] && in_array( 'SHOPEE_CONNECTION_NOT_READY', $no_shop->state( 10 )['warnings'], true ), 'No-connection path lost Excel result.' );
create_batch( 16, 1, 0 ); $many_shops = new Ecomkit_Vuikhoe_Auto_Pipeline( array( 'ready_connections' => static fn(): array => array( array( 'id' => 9 ), array( 'id' => 10 ) ), 'materialize' => static fn(): array => array( 'rows' => 1 ) ) ); $many_shops->start( 16 ); drain( $many_shops ); pipeline_check( 'WARNING' === $many_shops->state( 16 )['status'] && in_array( 'SHOP_SELECTION_REQUIRED', $many_shops->state( 16 )['warnings'], true ), 'Multiple shops were chosen arbitrarily.' );
create_batch( 13, 4, 4 ); $income_error_ops = $happy_ops; $income_error_ops['income_page'] = static function (): array { throw new RuntimeException( 'SHOPEE_INCOME_NETWORK_ERROR' ); }; $income_error = new Ecomkit_Vuikhoe_Auto_Pipeline( $income_error_ops ); $income_error->start( 13 ); drain( $income_error ); pipeline_check( 'WARNING' === $income_error->state( 13 )['status'] && 'WARNING' === $income_error->state( 13 )['income_status'] && 8 === $income_error->state( 13 )['counts']['canonical_rows'], 'Income provider error blocked Result.' );
create_batch( 17, 4, 4 ); $cursor_calls = array(); $cursor_ops = $happy_ops; $cursor_ops['income_page'] = static function ( int $connection_id, array $query, string $cursor ) use ( &$cursor_calls ): array { $cursor_calls[] = $cursor; return array( 'classification' => 'SUCCESS', 'records' => 'next' === $cursor ? array( array( 'order_sn' => 'TEST-SHP-003', 'estimated_escrow_amount' => 0 ) ) : array(), 'next_cursor' => '' === $cursor && 'PENDING' === $query['bucket'] ? 'next' : '', 'request_id' => 'cursor-safe' ); }; $cursor_count = 0; $cursor_ops['income_store'] = static function () use ( &$cursor_count ): void { $cursor_count++; }; $cursor_pipeline = new Ecomkit_Vuikhoe_Auto_Pipeline( $cursor_ops ); $cursor_pipeline->start( 17 ); drain( $cursor_pipeline ); pipeline_check( array( '', 'next' ) === array_slice( $cursor_calls, 0, 2 ) && 1 === $cursor_count && 8 === $cursor_pipeline->state( 17 )['counts']['canonical_rows'], 'Income cursor did not resume exactly or block-free.' );
create_batch( 15, 0, 2 ); $GLOBALS['schedule_failure'] = true; $schedule_fallback = new Ecomkit_Vuikhoe_Auto_Pipeline( array( 'materialize' => static fn(): array => array( 'rows' => 2 ) ) ); $schedule_fallback->start( 15 ); pipeline_check( 'QUEUED' === $schedule_fallback->state( 15 )['status'] && 0 === $schedule_fallback->state( 15 )['counts']['canonical_rows'] && ! $GLOBALS['scheduled'] && Ecomkit_Vuikhoe_Auto_Pipeline::progress( $schedule_fallback->state( 15 ) )['percent'] < 100, 'Cron scheduling failure falsely completed pipeline.' ); $GLOBALS['schedule_failure'] = false; $schedule_fallback->start( 15 ); drain( $schedule_fallback ); pipeline_check( 'WARNING' === $schedule_fallback->state( 15 )['status'] && 2 === $schedule_fallback->state( 15 )['counts']['canonical_rows'], 'Next ordinary page request did not recover scheduling.' );
create_batch( 18, 0, 2 ); $short_result = new Ecomkit_Vuikhoe_Auto_Pipeline( array( 'materialize' => static fn(): array => array( 'rows' => 1 ) ) ); $short_result->start( 18 ); drain( $short_result ); pipeline_check( 'ERROR' === $short_result->state( 18 )['status'] && Ecomkit_Vuikhoe_Auto_Pipeline::progress( $short_result->state( 18 ) )['percent'] < 100, 'Incomplete canonical row count falsely completed.' );
$admin_source = file_get_contents( __DIR__ . '/../ecomkit-vuikhoe/includes/class-ecomkit-admin.php' ); pipeline_check( str_contains( $admin_source, '->import_upload( $file' ) && str_contains( $admin_source, '->start( $batch_id )' ), 'Upload does not trigger pipeline.' );
$result_view = file_get_contents( __DIR__ . '/../ecomkit-vuikhoe/admin/views/results.php' ); pipeline_check( ! str_contains( $result_view, 'UI: Nền tảng / Matching / Cảnh báo' ) && str_contains( $result_view, "foreach ( \$result['columns'] as \$column )" ), 'Result table adds a noncanonical column.' );
pipeline_check( str_contains( $result_view, '<details><summary>' ) && str_contains( $result_view, 'Công cụ quản trị nâng cao' ) && str_contains( $result_view, 'Chỉ dùng khi cần kiểm tra kỹ thuật' ), 'Technical actions are prominent in normal Result view.' );
create_batch( 19, 0, 1 ); $gap_pipeline = new Ecomkit_Vuikhoe_Auto_Pipeline( array( 'materialize' => static fn(): array => array( 'rows' => 1, 'service_fee_source_gaps' => 1 ) ) ); $gap_pipeline->start( 19 ); drain( $gap_pipeline ); $gap_state = $gap_pipeline->state( 19 ); pipeline_check( 'WARNING' === $gap_state['status'] && 100 === Ecomkit_Vuikhoe_Auto_Pipeline::progress( $gap_state )['percent'] && in_array( 'SERVICE_FEE_SOURCE_GAP', $gap_state['warnings'], true ), 'Service fee source gap blocked completion or was not explained.' );
create_batch( 25, 2, 1 ); $zero_calls = array( 'payment' => 0, 'income' => 0 );
$zero_pipeline = new Ecomkit_Vuikhoe_Auto_Pipeline( array(
	'ready_connections' => static fn(): array => array( array( 'id' => 9 ) ),
	'reconcile' => static fn(): array => array( 'status' => 'WARNING', 'classification' => 'SHOPEE_RECON_PROVIDER_WINDOW_EMPTY', 'matched_count' => 0, 'missing_count' => 2, 'detail_count' => 0, 'total_windows' => 1, 'next_window_offset' => 1 ),
	'payment' => static function () use ( &$zero_calls ): void { $zero_calls['payment']++; },
	'income_page' => static function () use ( &$zero_calls ): array { $zero_calls['income']++; return array(); },
	'materialize' => static fn(): array => array( 'rows' => 3 ),
) );
$zero_pipeline->start( 25 ); drain( $zero_pipeline ); $zero_state = $zero_pipeline->state( 25 );
pipeline_check( 'WARNING' === $zero_state['status'] && 100 === Ecomkit_Vuikhoe_Auto_Pipeline::progress( $zero_state )['percent'] && 3 === $zero_state['counts']['canonical_rows'] && 0 === $zero_state['counts']['payment_total'] && array( 'payment' => 0, 'income' => 0 ) === $zero_calls && in_array( 'SHOPEE_RECON_PROVIDER_WINDOW_EMPTY', $zero_state['warnings'], true ), 'Zero-match pipeline called downstream provider or hid 3-row Result.' );
create_batch( 26, 11, 0 ); $recon_steps = 0; $detail_after_resume = 0;
$resume_ops = array(
	'ready_connections' => static fn(): array => array( array( 'id' => 9 ) ),
	'reconcile' => static function ( int $batch_id, int $connection_id, array $limits ) use ( &$recon_steps, $db ): array {
		$recon_steps++;
		pipeline_check( 9 === $connection_id && 0 === $limits['window_offset'], 'Reconciliation changed shop/window while paging.' );
		if ( $recon_steps < 3 ) { pipeline_check( $recon_steps - 1 === (int) ( $limits['continuation']['page_count'] ?? 0 ), 'Persisted cursor/page state was lost between cron events.' ); return array( 'status' => 'PROCESSING', 'total_windows' => 1, 'next_window_offset' => 0, 'continuation' => array( 'cursor' => 'page-' . $recon_steps, 'provider_ids' => array_fill_keys( range( 1, $recon_steps * 5 ), true ), 'page_count' => $recon_steps ) ); }
		pipeline_check( 2 === (int) ( $limits['continuation']['page_count'] ?? 0 ) && 10 === count( $limits['continuation']['provider_ids'] ), 'Third cron invocation did not receive all prior IDs.' );
		foreach ( $db->orders[ $batch_id ] as &$order ) { $order['matching_status'] = 'MATCHED'; } unset( $order );
		return array( 'status' => 'SUCCESS', 'matched_count' => 11, 'missing_count' => 0, 'detail_count' => 11, 'total_windows' => 1, 'next_window_offset' => 1 );
	},
	'payment' => static function ( int $batch_id, int $order_id ) use ( &$detail_after_resume ): void { $detail_after_resume++; },
	'income_page' => static fn(): array => array( 'classification' => 'SHOPEE_INCOME_EMPTY', 'records' => array(), 'next_cursor' => '', 'request_id' => 'safe' ),
	'materialize' => static fn(): array => array( 'rows' => 11 ),
);
$multi_cron = new Ecomkit_Vuikhoe_Auto_Pipeline( $resume_ops ); $multi_cron->start( 26 ); drain( $multi_cron ); $multi_state = $multi_cron->state( 26 );
pipeline_check( 3 === $recon_steps && 11 === $multi_state['counts']['shopee_matched'] && 11 === $multi_state['counts']['reconcile_checked'] && 11 === $multi_state['counts']['canonical_rows'] && 11 === $detail_after_resume && 100 === Ecomkit_Vuikhoe_Auto_Pipeline::progress( $multi_state )['percent'], 'Multi-cron 5+5+1 continuation did not run downstream 11-order pipeline.' );
$unresolved = $multi_state; $unresolved['status'] = 'WARNING'; $unresolved['counts']['reconcile_checked'] = 0; $unresolved['counts']['shopee_matched'] = 0;
pipeline_check( 0 === Ecomkit_Vuikhoe_Auto_Pipeline::progress( $unresolved )['reconcile_done'] && ! Ecomkit_Vuikhoe_Auto_Pipeline::progress( $unresolved )['terminal'] && Ecomkit_Vuikhoe_Auto_Pipeline::progress( $unresolved )['percent'] < 100, 'Terminal warning falsely completed 0/11 reconciliation.' );
create_batch( 27, 11, 0 ); $never_calls = 0; $never_ops = $resume_ops; $never_ops['reconcile'] = static function () use ( &$never_calls ): array { $never_calls++; return array( 'status' => 'SUCCESS', 'matched_count' => 0, 'missing_count' => 0, 'total_windows' => 1, 'next_window_offset' => 1 ); }; $never = new Ecomkit_Vuikhoe_Auto_Pipeline( $never_ops ); $never->start( 27 ); drain( $never ); $never_state = $never->state( 27 ); pipeline_check( 1 === $never_calls && 'ERROR' === $never_state['status'] && 0 === $never_state['counts']['reconcile_checked'] && 0 === $never_state['counts']['canonical_rows'] && in_array( 'SHOPEE_RECON_INCOMPLETE_STATE', $never_state['errors'], true ) && Ecomkit_Vuikhoe_Auto_Pipeline::progress( $never_state )['percent'] < 100, '11 eligible orders with no exact comparison reached terminal completion.' );
create_batch( 28, 11, 0 ); $early = new Ecomkit_Vuikhoe_Auto_Pipeline( $resume_ops ); $early->start( 28 ); $early_state = $early->state( 28 ); $early_state['counts']['canonical_rows'] = 11; $early_state['canonical_status'] = 'READY'; $early_state['stage'] = 'RESULT_READY'; $early_state['status'] = 'WARNING'; pipeline_check( ! Ecomkit_Vuikhoe_Auto_Pipeline::progress( $early_state )['terminal'] && Ecomkit_Vuikhoe_Auto_Pipeline::progress( $early_state )['percent'] < 100, 'Early 11 canonical rows hid pending reconciliation.' ); drain( $early );
create_batch( 29, 11, 0 ); $waiting = new Ecomkit_Vuikhoe_Auto_Pipeline( $resume_ops ); $waiting->start( 29 ); $waiting_progress = Ecomkit_Vuikhoe_Auto_Pipeline::progress( $waiting->state( 29 ) ); pipeline_check( 1 === count( $GLOBALS['scheduled'] ) && ! $waiting_progress['terminal'] && $waiting_progress['percent'] < 100 && 0 === $waiting_progress['reconcile_done'], 'Scheduled reconciliation was marked complete before Cron execution.' ); drain( $waiting );
create_batch( 30, 11, 0 ); $resume_once_ops = $resume_ops; $resume_once_ops['reconcile'] = static function ( int $batch_id ) use ( $db ): array { foreach ( $db->orders[ $batch_id ] as &$order ) { $order['matching_status'] = 'MATCHED'; } unset( $order ); return array( 'status' => 'SUCCESS', 'matched_count' => 11, 'missing_count' => 0, 'detail_count' => 11, 'total_windows' => 1, 'next_window_offset' => 1 ); }; $GLOBALS['schedule_failure'] = true; $schedule_block = new Ecomkit_Vuikhoe_Auto_Pipeline( $resume_once_ops ); $schedule_block->start( 30 ); pipeline_check( 'RECONCILE' === $schedule_block->state( 30 )['stage'] && ! Ecomkit_Vuikhoe_Auto_Pipeline::progress( $schedule_block->state( 30 ) )['terminal'], '11-order scheduling failure skipped reconciliation.' ); $GLOBALS['schedule_failure'] = false; $schedule_block->start( 30 ); drain( $schedule_block ); pipeline_check( 11 === $schedule_block->state( 30 )['counts']['reconcile_checked'], 'Pending 11-order reconciliation did not auto-resume on a later page request.' );
create_batch( 31, 11, 0 ); $blocked = new Ecomkit_Vuikhoe_Auto_Pipeline( array( 'ready_connections' => static fn(): array => array(), 'materialize' => static fn(): array => array( 'rows' => 11 ) ) ); $blocked->start( 31 ); drain( $blocked ); pipeline_check( 'SHOPEE_CONNECTION_NOT_READY' === $blocked->state( 31 )['reconciliation_block_reason'] && 0 === $blocked->state( 31 )['counts']['reconcile_checked'] && 100 === Ecomkit_Vuikhoe_Auto_Pipeline::progress( $blocked->state( 31 ) )['percent'], 'No-ready-shop lacked explicit terminal reason.' );
create_batch( 32, 11, 0 ); $ambiguous = new Ecomkit_Vuikhoe_Auto_Pipeline( array( 'ready_connections' => static fn(): array => array( array( 'id' => 1 ), array( 'id' => 2 ) ), 'materialize' => static fn(): array => array( 'rows' => 11 ) ) ); $ambiguous->start( 32 ); drain( $ambiguous ); pipeline_check( 'SHOP_SELECTION_REQUIRED' === $ambiguous->state( 32 )['reconciliation_block_reason'] && 0 === $ambiguous->state( 32 )['counts']['reconcile_checked'], 'Ambiguous shop lacked explicit terminal reason.' );
create_batch( 33, 11, 0 ); $legacy = new Ecomkit_Vuikhoe_Auto_Pipeline( $resume_once_ops ); $legacy->start( 33 ); $GLOBALS['scheduled'] = array(); $meta = json_decode( $db->batches[33]['source_metadata'], true ); $meta['auto_pipeline']['status'] = 'WARNING'; $meta['auto_pipeline']['stage'] = 'RESULT_READY'; $meta['auto_pipeline']['canonical_status'] = 'READY'; $meta['auto_pipeline']['counts']['canonical_rows'] = 11; $db->batches[33]['source_metadata'] = json_encode( $meta ); $legacy->start( 33 ); pipeline_check( 'QUEUED' === $legacy->state( 33 )['status'] && 'RECONCILE' === $legacy->state( 33 )['stage'] && 1 === count( $GLOBALS['scheduled'] ), 'Safe legacy 0/11 state did not restart required reconciliation.' ); drain( $legacy );
create_batch( 34, 11, 0 ); $uncertain = new Ecomkit_Vuikhoe_Auto_Pipeline( $resume_once_ops ); $uncertain->start( 34 ); $GLOBALS['scheduled'] = array(); $meta = json_decode( $db->batches[34]['source_metadata'], true ); $meta['auto_pipeline']['status'] = 'WARNING'; $meta['auto_pipeline']['stage'] = 'RESULT_READY'; $meta['auto_pipeline']['connection_id'] = 9; $meta['auto_pipeline']['counts']['canonical_rows'] = 11; $meta['auto_pipeline']['canonical_status'] = 'READY'; $db->batches[34]['source_metadata'] = json_encode( $meta ); $uncertain->start( 34 ); pipeline_check( 'WARNING' === $uncertain->state( 34 )['status'] && ! $GLOBALS['scheduled'] && ! Ecomkit_Vuikhoe_Auto_Pipeline::progress( $uncertain->state( 34 ) )['terminal'], 'Uncertain prior provider work was automatically repeated.' );
create_batch( 36, 11, 0 ); $early_event_calls = 0; $early_event = new Ecomkit_Vuikhoe_Auto_Pipeline( array( 'ready_connections' => static fn(): array => array( array( 'id' => 9 ) ), 'materialize' => static function () use ( &$early_event_calls ): array { $early_event_calls++; return array( 'rows' => 11 ); } ) ); $early_event->start( 36 ); $GLOBALS['scheduled'] = array(); $meta = json_decode( $db->batches[36]['source_metadata'], true ); $meta['auto_pipeline']['stage'] = 'MATERIALIZE'; $db->batches[36]['source_metadata'] = json_encode( $meta ); $early_event->run_one( 36 ); pipeline_check( 'ERROR' === $early_event->state( 36 )['status'] && 0 === $early_event_calls && in_array( 'SHOPEE_RECON_INCOMPLETE_STATE', $early_event->state( 36 )['errors'], true ), 'Out-of-order canonical worker finished before required reconciliation.' );
create_batch( 37, 11, 0 ); $local_calls = 0; $local = new Ecomkit_Vuikhoe_Auto_Pipeline( array( 'ready_connections' => static fn(): array => array( array( 'id' => 9 ) ), 'reconcile' => static function () use ( &$local_calls ): never { $local_calls++; throw new RuntimeException( 'SHOPEE_RECON_PERSIST_FAILED' ); }, 'materialize' => static fn(): array => array( 'rows' => 11 ) ) ); $local->start( 37 ); drain( $local ); $local_state = $local->state( 37 ); pipeline_check( 1 === $local_calls && 'SHOPEE_RECON_LOCAL_PERSIST_FAILED' === $local_state['reconciliation_block_reason'] && ! in_array( 'SHOPEE_RECON_PROVIDER_ERROR_TERMINAL', $local_state['warnings'], true ) && 100 === Ecomkit_Vuikhoe_Auto_Pipeline::progress( $local_state )['percent'], 'Local persistence error falsely became provider error.' );
create_batch( 38, 11, 0 ); $encode = new Ecomkit_Vuikhoe_Auto_Pipeline( array( 'ready_connections' => static fn(): array => array( array( 'id' => 9 ) ), 'reconcile' => static function (): never { throw new RuntimeException( 'SHOPEE_RECON_STATE_ENCODE_FAILED' ); }, 'materialize' => static fn(): array => array( 'rows' => 11 ) ) ); $encode->start( 38 ); drain( $encode ); pipeline_check( 'SHOPEE_RECON_LOCAL_PERSIST_FAILED' === $encode->state( 38 )['reconciliation_block_reason'], 'Encode failure misclassified as provider failure.' );
create_batch( 39, 1, 0 ); $locked_calls = 0; $locked = new Ecomkit_Vuikhoe_Auto_Pipeline( array( 'ready_connections' => static fn(): array => array( array( 'id' => 9 ) ), 'reconcile' => static function () use ( &$locked_calls ): array { $locked_calls++; return array( 'status' => 'WARNING', 'classification' => 'SHOPEE_RECON_PROVIDER_WINDOW_EMPTY', 'matched_count' => 0, 'missing_count' => 1, 'total_windows' => 1, 'next_window_offset' => 1 ); }, 'materialize' => static fn(): array => array( 'rows' => 1 ) ) ); $locked->start( 39 ); $GLOBALS['options']['ecomkit_pipeline_lock_39'] = time() + 180; $locked->run_one( 39 ); pipeline_check( 0 === $locked_calls && 'RECONCILE' === $locked->state( 39 )['stage'], 'Concurrent Cron worker bypassed Batch lock.' ); unset( $GLOBALS['options']['ecomkit_pipeline_lock_39'] ); drain( $locked ); pipeline_check( 1 === $locked_calls, 'Locked Batch did not safely continue once lock released.' );
echo "WP.6E one-upload pipeline checks passed.\n";
