<?php
/** WP.4A isolated Shopee refresh rotation and lock checks. */
declare(strict_types=1);
define( 'ABSPATH', __DIR__ . '/wordpress-placeholder/' ); define( 'ARRAY_A', 'ARRAY_A' ); define( 'ECOMKIT_CREDENTIAL_KEY', base64_encode( str_repeat( 'R', 32 ) ) );
function wp_json_encode( mixed $v, int $f = 0 ): string|false { return json_encode( $v, $f ); }
function get_option( string $k, mixed $d = false ): mixed { return $GLOBALS['opts'][$k] ?? $d; }
function update_option( string $k, mixed $v, bool $a = false ): bool { $GLOBALS['opts'][$k]=$v; return true; }
function current_time( string $t, bool $g=false ): string { return gmdate('Y-m-d H:i:s'); }
function rest_url( string $p ): string { return 'https://example.test/wp-json/'.$p; }
function wp_http_validate_url( string $u ): string|false { return filter_var($u,FILTER_VALIDATE_URL); }
function wp_parse_url( string $u, int $c=-1 ): mixed { return parse_url($u,$c); }
function add_query_arg( array $a, string $u ): string { return $u.'?'.http_build_query($a); }
function sanitize_text_field( string $v ): string { return trim(preg_replace('/[\x00-\x1F\x7F]/','',$v)); }
function sanitize_key( string $v ): string { return preg_replace('/[^a-z0-9_\-]/','',strtolower($v)); }
final class RefreshWpError {}
function is_wp_error( mixed $v ): bool { return $v instanceof RefreshWpError; }
function wp_remote_post( string $url, array $args ): mixed { $GLOBALS['calls'][]=compact('url','args'); return array_shift($GLOBALS['responses']); }
function wp_remote_retrieve_response_code( array $r ): int { return $r['status']; }
function wp_remote_retrieve_body( array $r ): string { return $r['body']; }
function refresh_check( bool $v, string $m ): void { if(!$v) throw new RuntimeException($m); }
final class RefreshWpdb {
	public string $prefix='refresh_'; public int $insert_id=0; public array $rows=array(); public int $lock_acquires=0; public bool $lock_available=true; public bool $fail_update=false;
	public function prepare(string $q,mixed ...$a): string { return json_encode(array('q'=>$q,'a'=>$a)); }
	public function get_var(string $q): mixed { $p=json_decode($q,true); $a=$p['a']; if(str_contains($p['q'],'GET_LOCK')) { $this->lock_acquires++; return $this->lock_available?1:0; } if(str_contains($p['q'],'RELEASE_LOCK')) return 1; foreach($this->rows as $id=>$r) if(($r['platform']??'')===($a[0]??'')&&($r['external_shop_id']??'')===($a[1]??'')) return $id; return 0; }
	public function get_row(string $q,string $o): ?array { $p=json_decode($q,true); return $this->rows[(int)$p['a'][0]]??null; }
	public function insert(string $t,array $d): int { $this->insert_id++; $this->rows[$this->insert_id]=$d+array('id'=>$this->insert_id); return 1; }
	public function update(string $t,array $d,array $w): int|false { if($this->fail_update) return false; $this->rows[$w['id']]=array_merge($this->rows[$w['id']],$d); return 1; }
}
$GLOBALS['wpdb']=new RefreshWpdb(); $GLOBALS['opts']=array(); $GLOBALS['calls']=array(); $GLOBALS['responses']=array();
foreach(array('class-ecomkit-db.php','class-ecomkit-credential-key-resolver.php','class-ecomkit-credential-encryption.php','class-ecomkit-credential-mutation-lock.php','class-ecomkit-shopee-environment.php','class-ecomkit-shopee-signer.php','class-ecomkit-shopee-config.php','class-ecomkit-shopee-http-client.php','class-ecomkit-marketplace-connection-service.php','class-ecomkit-shopee-token-service.php') as $file) require __DIR__.'/../ecomkit-vuikhoe/includes/'.$file;
$config_service=new Ecomkit_Vuikhoe_Shopee_Config(); $config=$config_service->save('sandbox','123','obviously-fake-partner-key'); $connections=new Ecomkit_Vuikhoe_Marketplace_Connection_Service();
$id=$connections->upsert_shopee('456',array('access_token'=>'ACCESS_A','refresh_token'=>'REFRESH_A','expire_in'=>3600),$config['fingerprint']); $service=new Ecomkit_Vuikhoe_Shopee_Token_Service();
$before=$GLOBALS['wpdb']->rows[$id]['credential_envelope']; refresh_check('ACCESS_A'===$service->ensure_usable_access_token($id)&&0===count($GLOBALS['calls'])&&$before===$GLOBALS['wpdb']->rows[$id]['credential_envelope'],'Usable token path refreshed or mutated credential.');
$GLOBALS['wpdb']->rows[$id]['credential_source']='EXTERNAL'; try{$service->ensure_usable_access_token($id,true);throw new RuntimeException('External credential refreshed.');}catch(RuntimeException $e){refresh_check('SHOPEE_REFRESH_NOT_OWNED'===$e->getMessage(),'Refresh ownership was not enforced.');} $GLOBALS['wpdb']->rows[$id]['credential_source']='OAUTH';
$changed=json_decode($GLOBALS['wpdb']->rows[$id]['metadata'],true); $changed['provider_config_fingerprint']='changed'; $GLOBALS['wpdb']->rows[$id]['metadata']=json_encode($changed); try{$service->ensure_usable_access_token($id,true);throw new RuntimeException('Changed config refreshed.');}catch(RuntimeException $e){refresh_check('SHOPEE_REFRESH_CONFIG_CHANGED'===$e->getMessage(),'Config fingerprint was not enforced.');} refresh_check(0===count($GLOBALS['calls']),'Ineligible connection called provider.');
$connections->upsert_shopee('456',array('access_token'=>'ACCESS_A','refresh_token'=>'REFRESH_A','expire_in'=>3600),$config['fingerprint']);
$GLOBALS['responses'][]=array('status'=>200,'body'=>json_encode(array('error'=>'','access_token'=>'ACCESS_B','refresh_token'=>'REFRESH_B','expire_in'=>600,'partner_id'=>123,'shop_id'=>456,'request_id'=>'refresh-1'))); $token=$service->ensure_usable_access_token($id,true);
$body=json_decode($GLOBALS['calls'][0]['args']['body'],true); refresh_check('ACCESS_B'===$token&&array('refresh_token','partner_id','shop_id')===array_keys($body)&&'REFRESH_A'===$body['refresh_token']&&is_int($body['partner_id'])&&is_int($body['shop_id']),'Refresh contract or first rotation failed.');
$crypto=new Ecomkit_Vuikhoe_Credential_Encryption(); $plain=$crypto->decrypt($GLOBALS['wpdb']->rows[$id]['credential_envelope'],'ecomkit|shopee|shop:456'); refresh_check('ACCESS_B'===$plain['access_token']&&'REFRESH_B'===$plain['refresh_token'],'Access/refresh pair was not atomically rotated.');
$call_count=count($GLOBALS['calls']); refresh_check('ACCESS_B'===$service->ensure_usable_access_token($id)&&$call_count===count($GLOBALS['calls']),'Second waiting request refreshed again instead of reloading fresh credential.');
$GLOBALS['responses'][]=array('status'=>200,'body'=>json_encode(array('error'=>'','access_token'=>'ACCESS_C','refresh_token'=>'REFRESH_C','expire_in'=>700))); $service->ensure_usable_access_token($id,true); $body2=json_decode($GLOBALS['calls'][1]['args']['body'],true); refresh_check('REFRESH_B'===$body2['refresh_token'],'Second refresh reused old single-use refresh token.');
$preserved=$GLOBALS['wpdb']->rows[$id]['credential_envelope']; $GLOBALS['responses'][]=new RefreshWpError(); try{$service->ensure_usable_access_token($id,true);throw new RuntimeException('Network ambiguity accepted.');}catch(Ecomkit_Vuikhoe_Shopee_Provider_Exception $e){refresh_check('SHOPEE_REFRESH_NETWORK_ERROR'===$e->getMessage(),'Network ambiguity classification wrong.');} $meta=json_decode($GLOBALS['wpdb']->rows[$id]['metadata'],true); refresh_check($preserved===$GLOBALS['wpdb']->rows[$id]['credential_envelope']&&'REFRESH_UNCERTAIN'===$meta['credential_lifecycle'],'Network ambiguity changed ciphertext or remained ready.');
$connections->upsert_shopee('456',array('access_token'=>'ACCESS_D','refresh_token'=>'REFRESH_D','expire_in'=>10),$config['fingerprint']); $GLOBALS['responses'][]=array('status'=>200,'body'=>json_encode(array('error'=>'refresh_token_expired','message'=>'expired','request_id'=>'refresh-expired'))); try{$service->ensure_usable_access_token($id,true);}catch(Ecomkit_Vuikhoe_Shopee_Provider_Exception $e){refresh_check('SHOPEE_REFRESH_REAUTH_REQUIRED'===$e->getMessage(),'Expired refresh mapping wrong.');} $meta=json_decode($GLOBALS['wpdb']->rows[$id]['metadata'],true); refresh_check('REAUTH_REQUIRED'===$meta['credential_lifecycle'],'Expired refresh did not require reauthorization.');
$connections->upsert_shopee('456',array('access_token'=>'ACCESS_E','refresh_token'=>'REFRESH_E','expire_in'=>10),$config['fingerprint']); $old=$GLOBALS['wpdb']->rows[$id]['credential_envelope']; $GLOBALS['responses'][]=array('status'=>200,'body'=>json_encode(array('error'=>'source_ip_undeclared','message'=>'whitelist IP','request_id'=>'ip'))); try{$service->ensure_usable_access_token($id,true);}catch(Ecomkit_Vuikhoe_Shopee_Provider_Exception $e){refresh_check('SHOPEE_SOURCE_IP_UNDECLARED'===$e->getMessage(),'Source IP mapping wrong.');} $meta=json_decode($GLOBALS['wpdb']->rows[$id]['metadata'],true); refresh_check($old===$GLOBALS['wpdb']->rows[$id]['credential_envelope']&&'READY'===$meta['credential_lifecycle'],'Source IP error destroyed or invalidated credential.');
$connections->upsert_shopee('456',array('access_token'=>'ACCESS_F','refresh_token'=>'REFRESH_F','expire_in'=>10),$config['fingerprint']); $identity_old=$GLOBALS['wpdb']->rows[$id]['credential_envelope']; $GLOBALS['responses'][]=array('status'=>200,'body'=>json_encode(array('error'=>'','access_token'=>'ACCESS_BAD','refresh_token'=>'REFRESH_BAD','expire_in'=>600,'partner_id'=>999,'shop_id'=>456))); try{$service->ensure_usable_access_token($id,true);}catch(Ecomkit_Vuikhoe_Shopee_Provider_Exception $e){refresh_check('SHOPEE_REFRESH_IDENTITY_MISMATCH'===$e->getMessage(),'Response identity mismatch accepted.');} refresh_check($identity_old===$GLOBALS['wpdb']->rows[$id]['credential_envelope'],'Identity mismatch overwrote credential.');
$connections->upsert_shopee('456',array('access_token'=>'ACCESS_G','refresh_token'=>'REFRESH_G','expire_in'=>10),$config['fingerprint']); $persist_old=$GLOBALS['wpdb']->rows[$id]['credential_envelope']; $GLOBALS['responses'][]=array('status'=>200,'body'=>json_encode(array('error'=>'','access_token'=>'ACCESS_H','refresh_token'=>'REFRESH_H','expire_in'=>600))); $GLOBALS['wpdb']->fail_update=true; try{$service->ensure_usable_access_token($id,true);}catch(RuntimeException $e){refresh_check('SHOPEE_REFRESH_PERSIST_FAILED'===$e->getMessage(),'Persistence failure classification wrong.');} $GLOBALS['wpdb']->fail_update=false; refresh_check($persist_old===$GLOBALS['wpdb']->rows[$id]['credential_envelope'],'Persistence failure partially overwrote credential pair.');
$GLOBALS['wpdb']->lock_available=false; try{$service->ensure_usable_access_token($id,true);throw new RuntimeException('Unavailable lock accepted.');}catch(RuntimeException $e){refresh_check('ECOMKIT_CREDENTIAL_LOCK_UNAVAILABLE'===$e->getMessage(),'Lock failure did not fail closed.');}
refresh_check(str_contains($GLOBALS['calls'][0]['url'],'/api/v2/auth/access_token/get')&&!str_contains($GLOBALS['calls'][0]['url'],'REFRESH_A')&&0===$GLOBALS['calls'][0]['args']['redirection'],'Refresh endpoint leaked token or followed redirects.');
refresh_check($GLOBALS['wpdb']->lock_acquires>=8,'Refresh and reauthorization did not share the connection lock.');
$admin_source=file_get_contents(__DIR__.'/../ecomkit-vuikhoe/includes/class-ecomkit-admin.php'); $view_source=file_get_contents(__DIR__.'/../ecomkit-vuikhoe/admin/views/marketplace.php');
refresh_check(str_contains($admin_source,"require_management_capability(); check_admin_referer( 'ecomkit_shopee_refresh_token'")&&str_contains($view_source,"wp_nonce_field( 'ecomkit_shopee_refresh_token'")&&!str_contains($view_source,'REFRESH_A'),'Manual refresh authorization or UI secret safety failed.');
echo "WP.4A Shopee token refresh lifecycle checks passed.\n";
