<?php
/** WP.4B synthetic-only Order API contract checks. */
declare(strict_types=1);
define('ABSPATH',__DIR__.'/wordpress-placeholder/'); define('ARRAY_A','ARRAY_A'); define('ECOMKIT_CREDENTIAL_KEY',base64_encode(str_repeat('Q',32)));
function wp_json_encode(mixed $v,int $f=0):string|false{return json_encode($v,$f);} function get_option(string $k,mixed $d=false):mixed{return $GLOBALS['opts'][$k]??$d;} function update_option(string $k,mixed $v,bool $a=false):bool{$GLOBALS['opts'][$k]=$v;return true;} function current_time(string $t,bool $g=false):string{return gmdate('Y-m-d H:i:s');}
function rest_url(string $p):string{return 'https://example.test/wp-json/'.$p;} function wp_http_validate_url(string $u):string|false{return filter_var($u,FILTER_VALIDATE_URL);} function wp_parse_url(string $u,int $c=-1):mixed{return parse_url($u,$c);} function add_query_arg(array $a,string $u):string{return $u.'?'.http_build_query($a);} function sanitize_text_field(string $v):string{return trim($v);} function sanitize_key(string $v):string{return preg_replace('/[^a-z0-9_\-]/','',strtolower($v));}
final class OrderWpError{} function is_wp_error(mixed $v):bool{return $v instanceof OrderWpError;} function wp_remote_get(string $u,array $a):mixed{$GLOBALS['get_calls'][]=compact('u','a');return array_shift($GLOBALS['get_responses']);} function wp_remote_post(string $u,array $a):array{$GLOBALS['post_calls'][]=compact('u','a');return array_shift($GLOBALS['post_responses']);} function wp_remote_retrieve_response_code(array $r):int{return $r['status'];} function wp_remote_retrieve_body(array $r):string{return $r['body'];} function order_check(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}
final class OrderWpdb{public string $prefix='order_';public int $insert_id=0;public array $rows=array();public function prepare(string $q,mixed ...$a):string{return json_encode(array('q'=>$q,'a'=>$a));}public function get_var(string $q):mixed{$p=json_decode($q,true);if(str_contains($p['q'],'GET_LOCK')||str_contains($p['q'],'RELEASE_LOCK'))return 1;foreach($this->rows as $id=>$r)if(($r['platform']??'')===($p['a'][0]??'')&&($r['external_shop_id']??'')===($p['a'][1]??''))return $id;return 0;}public function get_row(string $q,string $o):?array{$p=json_decode($q,true);return $this->rows[(int)$p['a'][0]]??null;}public function insert(string $t,array $d):int{$this->insert_id++;$this->rows[$this->insert_id]=$d+array('id'=>$this->insert_id);return 1;}public function update(string $t,array $d,array $w):int{$this->rows[$w['id']]=array_merge($this->rows[$w['id']],$d);return 1;}}
$GLOBALS['wpdb']=new OrderWpdb();$GLOBALS['opts']=array();$GLOBALS['get_calls']=array();$GLOBALS['post_calls']=array();$GLOBALS['get_responses']=array();$GLOBALS['post_responses']=array();
foreach(array('class-ecomkit-db.php','class-ecomkit-credential-key-resolver.php','class-ecomkit-credential-encryption.php','class-ecomkit-credential-mutation-lock.php','class-ecomkit-shopee-environment.php','class-ecomkit-shopee-signer.php','class-ecomkit-shopee-config.php','class-ecomkit-shopee-http-client.php','class-ecomkit-marketplace-connection-service.php','class-ecomkit-shopee-token-service.php','class-ecomkit-shopee-order-service.php')as$f)require __DIR__.'/../ecomkit-vuikhoe/includes/'.$f;
order_check('9cfafabdaef9cb9e0f061ea0c1e2f02e9101034bf1ab971945c714cbd054fbbb'===Ecomkit_Vuikhoe_Shopee_Signer::sign_shop('123','/api/v2/order/get_order_list',1700000000,'ACCESS_TOKEN','456','obviously-fake-partner-key'),'Shop signature vector failed.');
$config_service=new Ecomkit_Vuikhoe_Shopee_Config();$config=$config_service->save('sandbox','123','obviously-fake-partner-key');$connections=new Ecomkit_Vuikhoe_Marketplace_Connection_Service();$id=$connections->upsert_shopee('456',array('access_token'=>'ACCESS_A','refresh_token'=>'REFRESH_A','expire_in'=>3600),$config['fingerprint']);$orders=new Ecomkit_Vuikhoe_Shopee_Order_Service();
function response(array $data,int $status=200):array{return array('status'=>$status,'body'=>json_encode($data));}
$GLOBALS['get_responses'][]=response(array('error'=>'','request_id'=>'fake-list','response'=>array('more'=>true,'next_cursor'=>'OPAQUE-CURSOR-1','order_list'=>array(array('order_sn'=>'TEST-SHP-001','order_status'=>'COMPLETED')))));
$page=$orders->get_order_list_page($id,'create_time',1700000000,1700003600,100);$q=array();parse_str(parse_url($GLOBALS['get_calls'][0]['u'],PHP_URL_QUERY),$q);order_check(1===count($page['orders'])&&true===$page['more']&&'OPAQUE-CURSOR-1'===$page['next_cursor'],'List response parsing failed.');order_check(isset($q['partner_id'],$q['timestamp'],$q['access_token'],$q['shop_id'],$q['sign'],$q['time_from'],$q['time_to'])&&'order_status'===($q['response_optional_fields']??'')&&'ACCESS_A'===$q['access_token']&&0===count($GLOBALS['post_calls']),'Common shop query, optional status request, or valid-token integration failed.');order_check(Ecomkit_Vuikhoe_Shopee_Signer::sign_shop('123','/api/v2/order/get_order_list',(int)$q['timestamp'],'ACCESS_A','456','obviously-fake-partner-key')===$q['sign'],'Business filters entered shop signature base.');
$GLOBALS['get_responses'][]=response(array('error'=>'','request_id'=>'minimal','response'=>array('more'=>false,'order_list'=>array(array('order_sn'=>'TEST-MINIMAL')))));$minimal=$orders->get_order_list_page($id,'create_time',1700000000,1700003600,5);order_check(null===$minimal['orders'][0]['order_status']&&''===$minimal['next_cursor'],'List item without order_status or final page without cursor was rejected.');
$GLOBALS['get_responses'][]=response(array('error'=>'','request_id'=>'invalid','response'=>array('more'=>false,'next_cursor'=>'','order_list'=>array(array('order_status'=>'COMPLETED')))));try{$orders->get_order_list_page($id,'create_time',1700000000,1700003600,5);throw new RuntimeException('Missing order_sn accepted.');}catch(Ecomkit_Vuikhoe_Shopee_Order_Exception$e){order_check('SHOPEE_ORDER_RESPONSE_INVALID'===$e->getMessage()&&str_contains((string)($e->diagnostic['first_order_keys']??''),'order_status')&&!str_contains(json_encode($e->diagnostic),'TEST-'),'Missing order_sn classification or safe shape diagnostic failed.');}
$GLOBALS['get_responses'][]=response(array('error'=>'','request_id'=>'empty','response'=>array('more'=>false,'next_cursor'=>'','order_list'=>array())));$empty=$orders->get_order_list_page($id,'create_time',1700000000,1700003600,5);order_check(array()===$empty['orders']&&!$empty['more'],'Valid empty list failed.');$tz=new DateTimeZone('America/New_York');[$day_from,$day_to]=Ecomkit_Vuikhoe_Shopee_Order_Service::local_day_window('2026-09-17',$tz);order_check('2026-09-17 00:00:00'===(new DateTimeImmutable('@'.$day_from))->setTimezone($tz)->format('Y-m-d H:i:s')&&'2026-09-17 23:59:59'===(new DateTimeImmutable('@'.$day_to))->setTimezone($tz)->format('Y-m-d H:i:s'),'Date-only WordPress-timezone boundaries failed.');
foreach(array(array('TEST-1','A',true),array('TEST-1','B',true),array('TEST-2','',false))as[$sn,$cursor,$more])$GLOBALS['get_responses'][]=response(array('error'=>'','request_id'=>'p','response'=>array('more'=>$more,'next_cursor'=>$cursor,'order_list'=>array(array('order_sn'=>$sn,'order_status'=>'COMPLETED')))));
$all=$orders->get_all_orders($id,'update_time',1700000000,1700003600,100);order_check(2===count($all['orders'])&&1===$all['duplicate_count']&&3===$all['page_count'],'Pagination/dedup failed.');
$GLOBALS['get_responses'][]=response(array('error'=>'','response'=>array('more'=>true,'next_cursor'=>'A','order_list'=>array())));$GLOBALS['get_responses'][]=response(array('error'=>'','response'=>array('more'=>true,'next_cursor'=>'A','order_list'=>array())));try{$orders->get_all_orders($id,'create_time',1700000000,1700003600,5);throw new RuntimeException('Stalled cursor accepted.');}catch(Ecomkit_Vuikhoe_Shopee_Order_Exception$e){order_check('SHOPEE_ORDER_PAGINATION_STALLED'===$e->getMessage(),'Stall classification wrong.');}
for($n=1;$n<=100;$n++)$GLOBALS['get_responses'][]=response(array('error'=>'','response'=>array('more'=>true,'next_cursor'=>'LIMIT-'.$n,'order_list'=>array())));try{$orders->get_all_orders($id,'create_time',1700000000,1700003600,5);throw new RuntimeException('Page limit accepted.');}catch(Ecomkit_Vuikhoe_Shopee_Order_Exception$e){order_check('SHOPEE_ORDER_PAGE_LIMIT_EXCEEDED'===$e->getMessage(),'Page limit classification wrong.');}
$GLOBALS['get_responses'][]=response(array('error'=>'','request_id'=>'fake-detail','response'=>array('order_list'=>array(array('order_sn'=>'TEST-1','order_status'=>'COMPLETED','total_amount'=>100000,'item_list'=>array())))));
$detail=$orders->get_order_detail_page($id,array('TEST-1','TEST-2'),array('item_list'));order_check(array('TEST-2')===$detail['missing_order_sn']&&!$detail['complete']&&'TEST-1'===$detail['orders_by_sn']['TEST-1']['order_sn'],'Detail missing identity failed.');
$GLOBALS['get_responses'][]=response(array('error'=>'','response'=>array('order_list'=>array(array('order_sn'=>'TEST-1'),array('order_sn'=>'TEST-X')))));$extra=$orders->get_order_detail_page($id,array('TEST-1'));order_check(array('TEST-X')===$extra['extra_order_sn'],'Extra detail identity failed.');
$GLOBALS['get_responses'][]=response(array('error'=>'','response'=>array('order_list'=>array(array('order_sn'=>'TEST-1'),array('order_sn'=>'TEST-1')))));$duplicate=$orders->get_order_detail_page($id,array('TEST-1'));order_check(1===$duplicate['duplicate_count']&&!$duplicate['complete'],'Duplicate detail identity failed.');
$fifty=array_map(fn($n)=>'TEST-'.str_pad((string)$n,3,'0',STR_PAD_LEFT),range(1,50));$fifty_one=array_merge($fifty,array('TEST-051'));$GLOBALS['get_responses'][]=response(array('error'=>'','response'=>array('order_list'=>array_map(fn($sn)=>array('order_sn'=>$sn),$fifty))));order_check(50===$orders->get_order_detail_page($id,$fifty)['returned_count'],'Detail 50 failed.');try{$orders->get_order_detail_page($id,$fifty_one);throw new RuntimeException('Detail 51 low level accepted.');}catch(Ecomkit_Vuikhoe_Shopee_Order_Exception$e){order_check('SHOPEE_ORDER_DETAIL_BATCH_TOO_LARGE'===$e->getMessage(),'Detail 51 classification wrong.');}
$GLOBALS['get_responses'][]=response(array('error'=>'','response'=>array('order_list'=>array_map(fn($sn)=>array('order_sn'=>$sn),$fifty))));$GLOBALS['get_responses'][]=response(array('error'=>'','response'=>array('order_list'=>array(array('order_sn'=>'TEST-051')))));order_check(51===$orders->get_order_details_batched($id,$fifty_one)['returned_count'],'Detail batching 50+1 failed.');
foreach(array(array('create_time',1,1296002,5,'SHOPEE_ORDER_WINDOW_TOO_LARGE'),array('bad',1,2,5,'SHOPEE_ORDER_WINDOW_INVALID'),array('create_time',1,2,101,'SHOPEE_ORDER_PAGE_SIZE_INVALID'))as[$field,$from,$to,$size,$code])try{$orders->get_order_list_page($id,$field,$from,$to,$size);throw new RuntimeException('Invalid list input accepted.');}catch(Ecomkit_Vuikhoe_Shopee_Order_Exception$e){order_check($code===$e->getMessage(),'List input classification wrong.');}
try{$orders->get_order_detail_page($id,array('TEST-1'),array('secret_field'));throw new RuntimeException('Arbitrary optional field accepted.');}catch(Ecomkit_Vuikhoe_Shopee_Order_Exception$e){order_check('SHOPEE_ORDER_OPTIONAL_FIELD_INVALID'===$e->getMessage(),'Optional allowlist failed.');}
$meta=json_decode($GLOBALS['wpdb']->rows[$id]['metadata'],true);$meta['credential_lifecycle']='CONFIG_CHANGED';$GLOBALS['wpdb']->rows[$id]['metadata']=json_encode($meta);$calls=count($GLOBALS['get_calls']);try{$orders->get_order_list_page($id,'create_time',1,2,5);}catch(Ecomkit_Vuikhoe_Shopee_Order_Exception$e){order_check('SHOPEE_ORDER_CONNECTION_NOT_READY'===$e->getMessage(),'CONFIG_CHANGED not blocked.');}order_check($calls===count($GLOBALS['get_calls']),'Blocked connection called provider.');$meta['credential_lifecycle']='REFRESH_UNCERTAIN';$GLOBALS['wpdb']->rows[$id]['metadata']=json_encode($meta);try{$orders->get_order_list_page($id,'create_time',1,2,5);}catch(Ecomkit_Vuikhoe_Shopee_Order_Exception$e){order_check('SHOPEE_ORDER_CONNECTION_NOT_READY'===$e->getMessage(),'REFRESH_UNCERTAIN not blocked.');}
$meta['credential_lifecycle']='READY';$GLOBALS['wpdb']->rows[$id]['metadata']=json_encode($meta);foreach(array('source_ip_undeclared'=>'SHOPEE_SOURCE_IP_UNDECLARED','error_sign'=>'SHOPEE_SIGNATURE_INVALID','error_api_permission'=>'SHOPEE_ORDER_PERMISSION_DENIED','error_rate_limit'=>'SHOPEE_ORDER_RATE_LIMITED')as$error=>$code){$GLOBALS['get_responses'][]=response(array('error'=>$error,'message'=>'safe','request_id'=>'req'));try{$orders->get_order_list_page($id,'create_time',1,2,5);}catch(Ecomkit_Vuikhoe_Shopee_Order_Exception$e){order_check($code===$e->getMessage()&&'req'===$e->diagnostic['request_id'],'Provider mapping failed.');}}
$GLOBALS['get_responses'][]=response(array('error'=>'','response'=>array()),500);try{$orders->get_order_list_page($id,'create_time',1,2,5);}catch(Ecomkit_Vuikhoe_Shopee_Order_Exception$e){order_check('SHOPEE_ORDER_HTTP_ERROR'===$e->getMessage(),'HTTP error mapping failed.');}$GLOBALS['get_responses'][]=array('status'=>200,'body'=>'{bad');try{$orders->get_order_list_page($id,'create_time',1,2,5);}catch(Ecomkit_Vuikhoe_Shopee_Order_Exception$e){order_check('SHOPEE_ORDER_INVALID_JSON'===$e->getMessage(),'Invalid JSON mapping failed.');}
$GLOBALS['get_responses'][]=new OrderWpError();try{$orders->get_order_list_page($id,'create_time',1,2,5);}catch(Ecomkit_Vuikhoe_Shopee_Order_Exception$e){order_check('SHOPEE_ORDER_NETWORK_ERROR'===$e->getMessage(),'Network error mapping failed.');}
$crypto=new Ecomkit_Vuikhoe_Credential_Encryption();$plain=$crypto->decrypt($GLOBALS['wpdb']->rows[$id]['credential_envelope'],'ecomkit|shopee|shop:456');$plain['access_expires_at']=gmdate('Y-m-d H:i:s',time()+10);$GLOBALS['wpdb']->rows[$id]['credential_envelope']=$crypto->encrypt($plain,'ecomkit|shopee|shop:456');$GLOBALS['post_responses'][]=response(array('error'=>'','access_token'=>'ACCESS_NEW','refresh_token'=>'REFRESH_NEW','expire_in'=>600));$GLOBALS['get_responses'][]=response(array('error'=>'','response'=>array('more'=>false,'next_cursor'=>'','order_list'=>array())));$before_posts=count($GLOBALS['post_calls']);$before_gets=count($GLOBALS['get_calls']);$orders->get_order_list_page($id,'create_time',1,2,5);$last_url=$GLOBALS['get_calls'][count($GLOBALS['get_calls'])-1]['u'];order_check(1===count($GLOBALS['post_calls'])-$before_posts&&1===count($GLOBALS['get_calls'])-$before_gets&&str_contains($last_url,'access_token=ACCESS_NEW'),'Refreshed token was not used by Order request.');
$GLOBALS['get_responses'][]=response(array('error'=>'error_auth','message'=>'authorization invalid','request_id'=>'auth'));try{$orders->get_order_list_page($id,'create_time',1,2,5);}catch(Ecomkit_Vuikhoe_Shopee_Order_Exception$e){order_check('SHOPEE_ORDER_AUTH_ERROR'===$e->getMessage(),'Order auth error mapping failed.');}$reauth_meta=json_decode($GLOBALS['wpdb']->rows[$id]['metadata'],true);order_check('REAUTH_REQUIRED'===$reauth_meta['credential_lifecycle'],'Order auth evidence did not require reauthorization.');
foreach($GLOBALS['get_calls']as$call)order_check(!str_contains(json_encode($orders->last_diagnostic),'ACCESS_'),'Token leaked to diagnostics.');$admin=file_get_contents(__DIR__.'/../ecomkit-vuikhoe/includes/class-ecomkit-admin.php');$view=file_get_contents(__DIR__.'/../ecomkit-vuikhoe/admin/views/marketplace.php');order_check(str_contains($admin,"require_management_capability(); check_admin_referer( 'ecomkit_shopee_test_order_api'")&&str_contains($admin,'local_day_window')&&str_contains($admin,'array_slice')&&str_contains($admin, ', 0, 5')&&str_contains($view,'type="date"')&&!str_contains($view,'datetime-local'),'Admin date-only live test authorization/bound is missing.');echo "WP.4B.1 Shopee Order API alignment checks passed.\n";
