<?php defined( 'ABSPATH' ) || exit; $config = $data['shopee_config']; $ready = $data['shopee_readiness']; $key_ui = $data['partner_key_ui']; ?>
<div class="wrap"><h1><?php echo esc_html__( 'Marketplace', 'ecomkit-vuikhoe' ); ?></h1>
<?php if ( is_array( $data['oauth_diagnostic'] ?? null ) ) : $oauth_diag = $data['oauth_diagnostic']; ?><div class="notice notice-error inline"><p><strong>Safe OAuth diagnostics</strong></p><table class="widefat striped" style="max-width:760px"><tbody>
<tr><th>Stage</th><td><code><?php echo esc_html( (string) ( $oauth_diag['stage'] ?? '' ) ); ?></code></td></tr>
<tr><th>Classification</th><td><code><?php echo esc_html( (string) ( $oauth_diag['classification'] ?? '' ) ); ?></code></td></tr>
<?php if ( ! empty( $oauth_diag['provider_error'] ) ) : ?><tr><th>Shopee</th><td><code><?php echo esc_html( (string) $oauth_diag['provider_error'] ); ?></code></td></tr><?php endif; ?>
<?php if ( ! empty( $oauth_diag['provider_message'] ) ) : ?><tr><th>Safe provider message</th><td><?php echo esc_html( (string) $oauth_diag['provider_message'] ); ?></td></tr><?php endif; ?>
<?php if ( ! empty( $oauth_diag['request_id'] ) ) : ?><tr><th>Request ID</th><td><code><?php echo esc_html( (string) $oauth_diag['request_id'] ); ?></code></td></tr><?php endif; ?>
<?php if ( ! empty( $oauth_diag['http_status'] ) ) : ?><tr><th>HTTP status</th><td><?php echo esc_html( (string) $oauth_diag['http_status'] ); ?></td></tr><?php endif; ?>
<tr><th>API path</th><td><code><?php echo esc_html( (string) ( $oauth_diag['api_path'] ?? '' ) ); ?></code></td></tr>
</tbody></table></div><?php endif; ?>
<?php if ( ! $data['encryption_ready'] ) : ?><div class="notice notice-error inline"><p><?php echo esc_html__( 'WordPress Security Keys chưa đủ điều kiện để bảo vệ credential.', 'ecomkit-vuikhoe' ); ?></p></div><?php elseif ( 'WordPress Security Keys' === $data['key_source'] ) : ?><div class="notice notice-info inline"><p><?php echo esc_html__( 'Ecomkit đang sử dụng WordPress Security Keys để bảo vệ credential.', 'ecomkit-vuikhoe' ); ?></p></div><?php endif; ?>
<?php if ( isset( $_GET['shopee_notice'] ) ) : $notice = sanitize_key( wp_unslash( $_GET['shopee_notice'] ) ); ?><div class="notice notice-success inline"><p><?php echo esc_html( 'connected' === $notice ? __( 'Kết nối Shopee thành công.', 'ecomkit-vuikhoe' ) : ( 'partner_key_saved' === $notice ? __( 'Partner Key đã được lưu an toàn.', 'ecomkit-vuikhoe' ) : __( 'Cấu hình sẵn sàng — chưa gọi Shopee live.', 'ecomkit-vuikhoe' ) ) ); ?></p></div><?php endif; ?>
<?php if ( isset( $_GET['shopee_error'] ) ) : $error_code = strtoupper( sanitize_key( wp_unslash( $_GET['shopee_error'] ) ) ); ?><div class="notice notice-error inline"><p><?php echo esc_html( 'SHOPEE_INVALID_PARTNER_ID' === $error_code ? __( 'Partner ID không hợp lệ với môi trường hiện tại. Hãy kiểm tra Test/Live Partner ID và môi trường Sandbox/Production.', 'ecomkit-vuikhoe' ) : __( 'Thao tác Shopee không thành công.', 'ecomkit-vuikhoe' ) ); ?> <code><?php echo esc_html( $error_code ); ?></code><?php if ( isset( $_GET['request_id'] ) ) : ?> — Request ID: <code><?php echo esc_html( sanitize_text_field( wp_unslash( $_GET['request_id'] ) ) ); ?></code><?php endif; ?></p></div><?php endif; ?>
<h2><?php echo esc_html__( 'Cấu hình ứng dụng Shopee', 'ecomkit-vuikhoe' ); ?></h2>
<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="ecomkit_shopee_save_config"><?php wp_nonce_field( 'ecomkit_shopee_save_config', 'ecomkit_shopee_nonce' ); ?>
<table class="form-table"><tr><th><label for="shopee-environment"><?php echo esc_html__( 'Môi trường', 'ecomkit-vuikhoe' ); ?></label></th><td><select id="shopee-environment" name="environment"><option value="sandbox" <?php selected( $config['environment'] ?? '', 'sandbox' ); ?>>Sandbox</option><option value="production" <?php selected( $config['environment'] ?? '', 'production' ); ?>>Production</option></select><p class="description"><?php echo esc_html__( 'Sandbox chỉ dùng Test Partner ID/Key; Production chỉ dùng Live Partner ID/Key.', 'ecomkit-vuikhoe' ); ?></p></td></tr>
<tr><th><label for="shopee-partner-id">Partner ID</label></th><td><input id="shopee-partner-id" name="partner_id" value="<?php echo esc_attr( (string) ( $config['partner_id'] ?? '' ) ); ?>" inputmode="numeric" required></td></tr>
<tr><th><label for="shopee-partner-key">Partner Key</label></th><td><?php if ( 'not_configured' === $key_ui['state'] ) : ?><input id="shopee-partner-key" name="partner_key" type="password" value="" autocomplete="new-password"><p class="description"><?php echo esc_html__( 'Chưa cấu hình', 'ecomkit-vuikhoe' ); ?></p><?php elseif ( 'configured' === $key_ui['state'] ) : ?><span class="code" aria-label="Partner Key đã được che"><?php echo esc_html( $key_ui['mask'] ); ?></span><p class="description"><?php echo esc_html__( 'Đã lưu an toàn', 'ecomkit-vuikhoe' ); ?></p><?php else : ?><p><strong><?php echo esc_html( $key_ui['status'] ); ?></strong></p><p class="description"><?php echo esc_html__( 'Vui lòng nhập lại Partner Key và ủy quyền lại Shopee.', 'ecomkit-vuikhoe' ); ?></p><?php endif; ?></td></tr>
<tr><th><?php echo esc_html__( 'Callback URL', 'ecomkit-vuikhoe' ); ?></th><td><input type="url" class="regular-text code" readonly value="<?php echo esc_attr( $data['callback_url'] ); ?>"><p class="description"><?php echo esc_html__( 'Đăng ký domain/Redirect URL tương ứng trong Shopee Open Platform trước khi kết nối.', 'ecomkit-vuikhoe' ); ?></p></td></tr>
<tr><th><?php echo esc_html__( 'Trạng thái', 'ecomkit-vuikhoe' ); ?></th><td><strong><?php echo esc_html( $ready['ready'] ? 'READY' : 'INCOMPLETE' ); ?></strong></td></tr></table><?php submit_button( __( 'Lưu cấu hình', 'ecomkit-vuikhoe' ) ); ?></form>
<?php if ( 'not_configured' !== $key_ui['state'] ) : ?><details style="margin:12px 0"><summary class="button"><?php echo esc_html__( 'Thay đổi Partner Key', 'ecomkit-vuikhoe' ); ?></summary><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" style="margin-top:12px"><input type="hidden" name="action" value="ecomkit_shopee_replace_partner_key"><?php wp_nonce_field( 'ecomkit_shopee_replace_partner_key', 'ecomkit_shopee_nonce' ); ?><p><label for="shopee-partner-key-new"><strong><?php echo esc_html__( 'Partner Key mới', 'ecomkit-vuikhoe' ); ?></strong></label><br><input id="shopee-partner-key-new" name="partner_key_new" type="password" value="" autocomplete="new-password" required></p><?php submit_button( __( 'Lưu Partner Key mới', 'ecomkit-vuikhoe' ), 'primary', 'submit', false ); ?> <button type="button" class="button" onclick="this.closest('details').removeAttribute('open')"><?php echo esc_html__( 'Hủy', 'ecomkit-vuikhoe' ); ?></button></form></details><?php endif; ?>
<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" style="display:inline-block"><input type="hidden" name="action" value="ecomkit_shopee_test_config"><?php wp_nonce_field( 'ecomkit_shopee_test_config', 'ecomkit_shopee_nonce' ); ?><?php submit_button( __( 'Kiểm tra cấu hình', 'ecomkit-vuikhoe' ), 'secondary', 'submit', false ); ?></form>
<?php if ( $ready['ready'] ) : ?><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" style="display:inline-block;margin-left:8px"><input type="hidden" name="action" value="ecomkit_shopee_oauth_start"><?php wp_nonce_field( 'ecomkit_shopee_oauth_start', 'ecomkit_shopee_nonce' ); ?><?php submit_button( __( 'Kết nối Shopee', 'ecomkit-vuikhoe' ), 'primary', 'submit', false ); ?></form><?php endif; ?>
<hr><h2><?php echo esc_html__( 'Kết nối cửa hàng Shopee', 'ecomkit-vuikhoe' ); ?></h2>
<?php if ( empty( $data['connections'] ) ) : ?><p><?php echo esc_html__( 'Chưa kết nối cửa hàng.', 'ecomkit-vuikhoe' ); ?></p><?php else : foreach ( $data['connections'] as $connection ) : ?><div class="card"><h3><?php echo esc_html( 'Shop ID: ' . $connection['external_shop_id'] ); ?></h3><p><strong><?php echo esc_html( $connection['credential_ready'] ? 'CONNECTED / Đã kết nối' : 'Cần ủy quyền lại' ); ?></strong></p><p>Credential source: OAuth<br>Access Token: Đã lưu an toàn<br>Refresh Token: Đã lưu an toàn<br>Refresh: Ecomkit quản lý<br><?php echo esc_html__( 'Access Token hết hạn:', 'ecomkit-vuikhoe' ); ?> <?php echo esc_html( $connection['access_expires_at'] ? wp_date( get_option( 'date_format' ) . ' ' . get_option( 'time_format' ), strtotime( (string) $connection['access_expires_at'] . ' UTC' ), wp_timezone() ) : 'N/A' ); ?></p><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="ecomkit_shopee_oauth_start"><?php wp_nonce_field( 'ecomkit_shopee_oauth_start', 'ecomkit_shopee_nonce' ); ?><?php submit_button( __( 'Ủy quyền lại', 'ecomkit-vuikhoe' ), 'secondary', 'submit', false ); ?></form></div><?php endforeach; endif; ?></div>
